package org.example.project.screens.journey

import androidx.compose.ui.graphics.Color
import org.example.project.theme.MythColors

enum class Trait(val display: String, val color: Color) {
    Courage("Courage", MythColors.Crimson),
    Wisdom("Wisdom", MythColors.Sky),
    Cunning("Cunning", MythColors.Emerald),
    Compassion("Compassion", MythColors.GoldBright),
}

data class QuizOption(
    val label: String,
    val fragment: String,
    val trait: Trait,
)

data class QuizQuestion(
    val prompt: String,
    val options: List<QuizOption>,
)

data class QuizChapter(
    val chapterId: String,
    val title: String,
    val subtitle: String,
    val realm: String,
    val accent: Color,
    val opening: String,
    val closing: String,
    val questions: List<QuizQuestion>,
)

private fun q(
    prompt: String,
    l1: String, f1: String, t1: Trait,
    l2: String, f2: String, t2: Trait,
    l3: String, f3: String, t3: Trait,
    l4: String, f4: String, t4: Trait,
) = QuizQuestion(
    prompt,
    listOf(
        QuizOption(l1, f1, t1),
        QuizOption(l2, f2, t2),
        QuizOption(l3, f3, t3),
        QuizOption(l4, f4, t4),
    )
)

private val C = Trait.Courage
private val W = Trait.Wisdom
private val X = Trait.Cunning
private val M = Trait.Compassion

object QuizCatalog {

    private val delphi = QuizChapter(
        chapterId = "delphi",
        title = "The Oracle's Warning",
        subtitle = "Delphi by moonlight",
        realm = "Hellas",
        accent = MythColors.Gold,
        opening = "Smoke rises from the chasm at Delphi. I have climbed here on foot, one silver coin in my hand, one unasked question in my heart.",
        closing = "The Pythia speaks a word I do not know. I leave before dawn, the coin still warm in my palm, and I do not look back.",
        questions = listOf(
            q("The priest asks what you seek.",
                "Truth at any cost", "I answered that I came for truth, whatever the cost.", C,
                "Safety for my house", "I said I wished only to shield my household.", M,
                "My enemy's name", "I asked the name of the one who would ruin me.", X,
                "A road unwalked", "I asked for a road no traveller has found.", W),
            q("The chasm exhales a pale smoke.",
                "Breathe it in", "I breathed the vapour and felt the world tilt.", C,
                "Step back", "I stepped back, my hand pressed to my chest.", W,
                "Watch its shape", "I watched how it coiled and saw a serpent's shape.", X,
                "Pray quietly", "I murmured a prayer that only the stones could hear.", M),
            q("The Pythia begins to chant low.",
                "Close my eyes", "I closed my eyes and let her voice become the world.", W,
                "Lean closer", "I leaned in so near I could feel her breath.", C,
                "Study her face", "I studied the sweat and the faraway light in her eyes.", X,
                "Offer my coin", "I placed my coin upon the tripod before she ended.", M),
            q("She speaks in riddles of a two-edged fate.",
                "Accept both edges", "I swore I would carry both fates if I must.", C,
                "Seek the hidden door", "I asked for the third way her words concealed.", X,
                "Beg for a kinder sign", "I begged her to give a gentler word for my people.", M,
                "Write her words down", "I pressed her words into wax before they faded.", W),
            q("A bronze tripod rings of its own accord.",
                "Kneel before it", "I knelt and let the tripod's note move through my bones.", M,
                "Touch the metal", "I touched the rim and felt a warning pass from the god.", C,
                "Count its trembles", "I counted the strokes and stored the number for later.", X,
                "Mark its silence after", "I noted the silence that followed and the weight of it.", W),
            q("An eagle wheels once above the sanctuary.",
                "Name it an omen", "I named the eagle a sign from Zeus and took heart.", C,
                "Watch where it flies", "I watched where it went so I might walk the same road.", X,
                "Offer thanks aloud", "I gave thanks aloud, so the god would not be ignored.", M,
                "Commit its turn to memory", "I committed each curve of its turn to memory.", W),
            q("A priest offers you water from the Castalian spring.",
                "Drink and swear", "I drank and swore silence upon its cool weight.", M,
                "Ask its price first", "I asked what the draught would cost before I drank.", X,
                "Pour a little to earth", "I poured a measure to earth for those who could not drink.", M,
                "Study the surface", "I studied my reflection and saw someone I did not yet know.", W),
            q("An old soldier kneels beside you, weeping.",
                "Lift him up", "I raised him gently and said the god's word was not despair.", M,
                "Ask his name", "I asked his name, so I might carry his grief with mine.", M,
                "Walk on quietly", "I walked on, unwilling to break his private hour.", W,
                "Share my coin", "I pressed half my coin into his hand without speaking.", M),
            q("The oracle's word, reread, could mean war or sea-crossing.",
                "Trust war", "I told myself war was the harder path, and chose it.", C,
                "Trust the sea", "I said the sea was older than any blade, and chose it.", W,
                "Split the message", "I split the message into two tasks and took both.", X,
                "Ask a second reader", "I asked an old scholar to read the verse again with me.", M),
            q("A scribe at the threshold offers to record your question.",
                "Let him write", "I let him write it down, so others could one day read.", W,
                "Refuse", "I refused; some questions must stay between one mouth and one god.", C,
                "Bargain for the tablet", "I bargained for the tablet itself and tucked it away.", X,
                "Dictate a second version", "I dictated a gentler version for my people to hear.", M),
            q("At the last, the Pythia names a star.",
                "Walk toward it", "I set out in the dark toward that star and did not stop.", C,
                "Number its neighbours", "I numbered the stars around it, to find it again at sea.", W,
                "Scratch its mark on my cloak", "I scratched its mark on my cloak so I would not forget.", X,
                "Name it for a friend", "I gave the star the name of a friend I had lost.", M),
            q("The threshold guardian asks what you will carry away.",
                "A vow", "I told him I carried a vow, and he let me pass.", C,
                "A question", "I said a question, deeper than the one I arrived with.", W,
                "An ember", "I told him an ember, small enough to hide in a fist.", X,
                "A kindness", "I said a kindness I had not yet learned to give.", M),
        )
    )

    private val hades = QuizChapter(
        chapterId = "hades",
        title = "Beneath the Black Sail",
        subtitle = "Crossing Charon's river",
        realm = "Hellas",
        accent = MythColors.Azure,
        opening = "The rushes part and the river stretches wide, grey as beaten pewter. I step into the boat with a coin in my cheek and a name I must not forget.",
        closing = "I climb again into the upper air with dust in my lungs and one more life to live. The river runs silver behind me. I do not turn.",
        questions = listOf(
            q("Charon asks for the fare.",
                "Surrender my coin", "I gave him the coin and kept my gaze upon his eyes.", C,
                "Bargain for passage", "I bargained, offering a song instead of silver.", X,
                "Show him the name I seek", "I showed him the name and his grip softened.", M,
                "Recite my lineage", "I named my fathers, and he nodded me onto the boat.", W),
            q("A shade tries to board with you.",
                "Let him aboard", "I made room for him, though the boat lay low in the water.", M,
                "Refuse gently", "I told him his hour was not yet, and he drifted off.", W,
                "Ask his story", "I asked his story and held it like a candle.", M,
                "Trade coins with him", "I pressed my coin to his palm and took his in return.", X),
            q("The far bank appears, roofless and grey.",
                "Step off first", "I leapt to the bank before Charon could speak again.", C,
                "Wait to be bid", "I waited for his word before I stepped ashore.", W,
                "Lay my cloak on the ground", "I spread my cloak so no ghost would touch bare stone.", M,
                "Mark the spot", "I carved a sign in the stone so I could find it again.", X),
            q("Cerberus wakes, three heads lifting.",
                "Sing to each head", "I sang three different songs, one to each throat.", W,
                "Offer a barley cake", "I offered the cake Persephone's women had given me.", M,
                "Speak my name loudly", "I spoke my name loudly, so he would remember me.", C,
                "Slip past in silence", "I slipped past while all three heads turned to the noise above.", X),
            q("Fields of asphodel whisper around your feet.",
                "Listen for one voice", "I listened past the chorus for the one name I knew.", M,
                "Walk steadily through", "I walked steadily, refusing to stop for any voice.", C,
                "Kneel and ask a question", "I knelt and asked the field for the name's path.", W,
                "Hold my breath a while", "I held my breath, so the dust would not enter me.", X),
            q("A former teacher rises from the grey.",
                "Bow to him", "I bowed to him, for he had given me my first word.", M,
                "Ask his last lesson", "I asked for his final lesson and he gave it like bread.", W,
                "Beg his forgiveness", "I begged forgiveness for the oath I had broken.", M,
                "Promise him a libation", "I vowed to pour wine for him when I saw the sun again.", M),
            q("You come upon a river of fire.",
                "Leap across", "I leapt, and the flames licked only my heel.", C,
                "Walk upstream for a ford", "I walked the bank until I found a place of shallower flame.", W,
                "Cover my head with a cloak", "I covered my head and crossed where the smoke hid me.", X,
                "Pray to Hestia", "I prayed to Hestia and stepped in, and the fire let me pass.", M),
            q("Persephone watches you from a distance.",
                "Offer her a pomegranate seed", "I offered the seed I had kept, and she almost smiled.", M,
                "Meet her eyes", "I met her eyes and held them until she nodded.", C,
                "Kneel in silence", "I knelt and said nothing, for silence was respect enough.", W,
                "Plead my errand", "I pleaded my errand and she pointed with her thinnest finger.", X),
            q("Hades' court opens: a hall of dark lilies.",
                "Kneel before the throne", "I knelt and kept my forehead on the cold stone.", W,
                "State my errand plainly", "I spoke my errand in a voice that did not tremble.", C,
                "Offer the king a gift", "I offered a coin from the upper world as tribute.", M,
                "Speak his title thrice", "I spoke his titles thrice, and he inclined his head.", W),
            q("The soul you seek is brought before you.",
                "Embrace them", "I opened my arms, though I knew I could not hold a shade.", M,
                "Speak their true name", "I said the name only we two had ever used.", M,
                "Apologise", "I said the thing I had not said while they were living.", M,
                "Ask their will", "I asked if they wished to return — and listened to the answer.", W),
            q("Hades asks: what will you leave in exchange?",
                "A year of my years", "I offered a year of my own life, and he weighed it.", C,
                "My voice", "I offered my singing voice; he considered it in silence.", M,
                "My memory of my father", "I offered the memory of my father; he refused.", X,
                "My most true name", "I offered my truest name, spoken only by one still living.", W),
            q("You climb the spiral stair toward the upper air.",
                "Do not look back", "I kept my eyes forward, and heard the step behind me.", C,
                "Risk one glance", "I turned once, and what I saw I cannot speak.", C,
                "Count my steps", "I counted two hundred and sixty-three and reached the light.", X,
                "Speak no word till dawn", "I climbed in silence and did not speak until the sun rose.", W),
        )
    )

    private val bifrost = QuizChapter(
        chapterId = "bifrost",
        title = "The Bridge of Flame",
        subtitle = "Ragnarök's first night",
        realm = "Skandia",
        accent = MythColors.Sky,
        opening = "Heimdall's horn sounds once. I run for the bridge because someone must, and because I heard the call before I could pretend not to.",
        closing = "Morning comes grey over broken stone. The bridge is gone. I am still here. I do not know yet if that is mercy or punishment.",
        questions = listOf(
            q("Heimdall places a horn in your hand.",
                "Blow it for Asgard", "I raised the horn and set Asgard ringing in my ears.", C,
                "Ask whom to summon", "I asked him which gods still answered the call.", W,
                "Pass it to another", "I pressed the horn into the hand of a braver soldier.", M,
                "Keep it hidden at my belt", "I hid the horn at my belt for a later, darker hour.", X),
            q("The first giant strides toward the bridge.",
                "Meet him on open ground", "I met him alone where the bridge met the rock.", C,
                "Set traps on the ramp", "I scored the stone so he would stumble on his march.", X,
                "Call for Thor aloud", "I called Thor's name into the storm and was answered.", C,
                "Guard the eastern gate", "I ran to the eastern gate, where civilians fled.", M),
            q("Heimdall offers you Gjallarhorn's old tune.",
                "Learn the tune", "I learned the four notes, so the horn might sound through me.", W,
                "Refuse the burden", "I refused; some songs belong to their first singer.", W,
                "Play the tune slowly", "I played it slowly, as a dirge for what we were losing.", M,
                "Teach the tune to a child", "I taught the tune to a child fleeing past me.", M),
            q("Wolves run along the ridge below.",
                "Rally the spearmen", "I rallied the spearmen with a name older than fear.", C,
                "Let them pass", "I let the wolves run; they were not my quarrel this hour.", W,
                "Count them", "I counted them and sent the count to Odin's ravens.", X,
                "Call the shield-maidens", "I called the shield-maidens who had no one else to guard them.", M),
            q("A god staggers past you, bleeding silver.",
                "Bind the wound", "I tore a strip from my cloak and bound the god's arm.", M,
                "Lift him to safety", "I carried him back from the line so he could breathe.", M,
                "Ask his last command", "I asked his last command, and he gave me one word.", W,
                "Swear vengeance", "I swore vengeance upon the one who had struck him.", C),
            q("The sky cracks. A wyrm of fire climbs the sea.",
                "Stand and face it", "I stood at the bridge's centre with my sword lifted.", C,
                "Rouse the giants' foe", "I shouted for Thor to turn from his wolf to the wyrm.", C,
                "Lead the children below", "I led the children to cellars we had dug in patient years.", M,
                "Ready my bow", "I readied my bow; one arrow for one eye.", X),
            q("An ally falls into the foam below.",
                "Leap after them", "I leapt without thought and caught them by the wrist.", C,
                "Throw a rope", "I threw the rope I had carried for this very hour.", X,
                "Mark the place", "I marked the place with stones and promised to return.", W,
                "Name them to the Norns", "I named them to the Norns so their thread would not be lost.", M),
            q("Heimdall falters. The bridge groans beneath your feet.",
                "Take his place", "I took his place at the ward, though I was not worthy.", C,
                "Shoulder him back", "I shouldered him upright so he could keep his watch.", M,
                "Run for reinforcements", "I ran for those still behind the ward, calling their names.", X,
                "Call Skadi from the snows", "I called Skadi's name into the snows, and was answered.", W),
            q("Loki laughs from the middle of the storm.",
                "Face him directly", "I stepped into the storm and asked him his grievance.", C,
                "Ignore his taunts", "I ignored his words and held my ground on the bridge.", W,
                "Answer his riddle", "I answered his riddle and his laughter changed its tone.", X,
                "Pity him aloud", "I pitied him aloud, which wounded him more than a blade.", M),
            q("A raven lands on your shoulder.",
                "Listen to its word", "I listened; the raven named a danger I had not yet seen.", W,
                "Send it back to Odin", "I sent the raven back with a tally of what we had lost.", X,
                "Feed it from my hand", "I fed it the last bread I carried, and it ate politely.", M,
                "Trust nothing it says", "I remembered who owns ravens, and gave it nothing.", W),
            q("Morning will come soon. Someone must hold the gap.",
                "Volunteer", "I told them I would stand the last hour, and they believed me.", C,
                "Choose a watch together", "I helped draw lots so no one stood alone.", M,
                "Offer my banner", "I gave them my banner to raise when the light returned.", M,
                "Sing them a battle-song", "I sang them the song my grandmother taught me for mornings like this.", M),
            q("At the last, you hear the horn one more time.",
                "Answer with a shout", "I answered with a shout that shook ice from the bridge.", C,
                "Bow my head", "I bowed my head and let the horn's note pass through me.", W,
                "Run toward the sound", "I ran toward the sound, even as the stone fell behind me.", C,
                "Close my eyes", "I closed my eyes and counted my breaths until it ended.", W),
        )
    )

    private val osiris = QuizChapter(
        chapterId = "osiris",
        title = "Halls of Osiris",
        subtitle = "The weighing of the heart",
        realm = "Kemet",
        accent = MythColors.Emerald,
        opening = "The jackal leads me by a corridor I did not know my body could walk. At its end: a scale, a feather, and the quiet eyes of the lord of the dead.",
        closing = "The feather lifts. The scale settles. A scribe with an ibis head writes my name in a column that has no end. I am given leave to continue.",
        questions = listOf(
            q("Anubis offers his arm at the threshold.",
                "Accept the guidance", "I accepted his arm and let him lead me without fear.", W,
                "Kneel in greeting", "I knelt, offering the oldest courtesy of my people.", M,
                "Ask his secret name", "I asked his secret name, since I was a guest here.", X,
                "Recite a prayer", "I recited the prayer my mother had taught me as a child.", M),
            q("The scribe of ibis reads your first confession.",
                "Speak the truth", "I spoke the truth in a voice that did not waver.", C,
                "Begin with my worst", "I began with my heaviest deed and let the rest rise lighter.", W,
                "Speak the brightest first", "I opened with what I loved most, so it would be heard.", M,
                "Ask to be reminded", "I asked the scribe to remind me of deeds I had forgotten.", X),
            q("Ma'at's feather is placed upon the scale.",
                "Remove my rings", "I took off my rings so only my heart would weigh the pan.", M,
                "Breathe out slowly", "I breathed out slowly and let the weight find its level.", W,
                "Offer my name first", "I offered my true name to the pan before my heart.", M,
                "Watch the feather closely", "I watched the feather's edge, for it told more than the scale.", X),
            q("Your heart is lifted and placed opposite the feather.",
                "Whisper the oath of the heart", "I whispered the oath so my heart would not betray me.", W,
                "Let it be weighed as it is", "I let it be weighed without advocacy, deeds plain.", C,
                "Name my deepest kindness", "I named the kindest thing I had ever done aloud.", M,
                "Name my deepest fault", "I named my worst fault openly, so it could not be found later.", W),
            q("A crocodile waits beyond the scale.",
                "Face Ammit without flinching", "I faced Ammit without flinching, counting breaths.", C,
                "Speak the god's name softly", "I spoke Ammit's name softly so she would know mine.", W,
                "Plead my case aloud", "I pleaded my case before the court, not to her.", C,
                "Remember the living", "I remembered those still living, and held them in mind.", M),
            q("Osiris raises his crook and flail.",
                "Bow lower", "I bowed lower than I thought I could, forehead to stone.", M,
                "Meet his eyes", "I met his eyes without pretence to innocence.", C,
                "Offer what I carried", "I offered the small blue scarab I had kept all my life.", M,
                "Recite his seventy-two names", "I recited the first seventy-two of his names.", W),
            q("The forty-two judges each ask a confession.",
                "Answer each truthfully", "I answered each judge, one by one, without shortcut.", C,
                "Answer in one single vow", "I gave them one vow to cover forty-two lifetimes.", W,
                "Beg forgiveness when needed", "I asked pardon where pardon was mine to beg.", M,
                "Offer silent amends", "I promised, silently, to pay a deed to a living kin.", M),
            q("A small door opens beside the hall.",
                "Step through it", "I stepped through the door, without waiting to be told.", C,
                "Wait to be called", "I waited for a call, since the hall had been careful so far.", W,
                "Ask where it leads", "I asked the jackal where the door would take me.", W,
                "Mark it in memory", "I noted the door's shape so I might return one day.", X),
            q("The Book of Going Forth is opened.",
                "Sign my own chapter", "I signed a chapter that had been left blank for me.", C,
                "Read what was written already", "I read the page carefully and saw a life I had almost lived.", W,
                "Add a kindness to the record", "I added one kindness that no one had seen me do.", M,
                "Strike one false line out", "I struck one false line, for no book should keep that lie.", W),
            q("Isis lifts her wings and offers you breath.",
                "Accept the breath", "I accepted her breath and felt each rib open again.", C,
                "Offer it onward", "I passed her breath to a shade still gasping behind me.", M,
                "Ask for a sister's breath too", "I asked a second breath for my sister, who was not here.", M,
                "Bow silently", "I bowed silently and let her wings cover me for a while.", M),
            q("Horus beckons you toward the farther gate.",
                "Rise and follow", "I rose and followed him without asking where.", C,
                "Take Horus's hand", "I took his offered hand; his fingers were warm as falcon down.", M,
                "Look one last time", "I looked back once at the scale and the feather still level.", W,
                "Leave an offering", "I left an amulet on the threshold for the next arrival.", M),
            q("The last gate asks: what do you bring to the fields?",
                "A hand for work", "I said I would bring a hand willing for any work.", C,
                "A kindness for strangers", "I said I would bring a kindness never yet given.", M,
                "A memory", "I said a memory the dead had asked me to deliver.", W,
                "A song", "I said a song, so the fields would be louder at dawn.", M),
        )
    )

    private val avalon = QuizChapter(
        chapterId = "avalon",
        title = "Avalon's Mist",
        subtitle = "The apple-isle",
        realm = "Albion",
        accent = MythColors.Emerald,
        opening = "The boatwoman rows without speaking. The mist peels back and the apple trees lean out of their own shadows, white-flowered though no season should allow it.",
        closing = "The mist closes behind me. I sleep one night and wake in my own bed, with a cut palm I cannot explain and a song on my tongue I did not know.",
        questions = listOf(
            q("The boatwoman asks whom you seek.",
                "The sleeping king", "I said I sought the king who has not yet returned.", W,
                "A cure for my sister", "I said I came for a cure my sister could not find.", M,
                "A truth denied to me", "I said I came for a truth the mainland hid from me.", X,
                "Only the way back", "I asked only how to find my way home afterwards.", W),
            q("Nine sisters rise from the orchard to meet you.",
                "Name each one I know", "I named each of the sisters whose names I had learned.", M,
                "Ask the eldest's counsel", "I asked the eldest what she would have me do.", W,
                "Offer a gift to the youngest", "I gave the youngest a small cloth wrapped from my journey.", M,
                "Keep silent", "I kept silent, as I had been told the isle preferred.", W),
            q("Morgan herself walks through the trees.",
                "Bow without speaking", "I bowed without a word, for she had earned it.", M,
                "Ask her mercy for a friend", "I asked her mercy for a friend not yet saved.", M,
                "Offer service in return", "I offered a year of service in return for her aid.", C,
                "Meet her gaze steady", "I met her gaze steadily; she did not look away first.", C),
            q("A deep well sits at the orchard's heart.",
                "Drink deeply", "I drank from the well and tasted every spring I had known.", C,
                "Offer a coin", "I offered a coin I had been keeping for just such a well.", M,
                "Study its reflection", "I studied the reflection and saw a face that was not mine.", W,
                "Ask whose it is", "I asked whose well it was, and the sisters laughed gently.", X),
            q("The sisters show you a wound that will not close.",
                "Lay on hands", "I laid my hands to the wound as they showed me.", M,
                "Bring water from the well", "I brought water from the well and washed it clean.", M,
                "Learn the binding song", "I learned the song that closes such wounds in the slow way.", W,
                "Sit through the night with it", "I sat the night beside it, so its owner would not be alone.", M),
            q("Arthur's sleeping form is shown to you.",
                "Kneel in greeting", "I knelt and spoke his titles aloud to the silent chamber.", M,
                "Wake him", "I tried, briefly, to wake him, and felt the isle refuse.", C,
                "Whisper a message", "I whispered news from the upper world and he almost smiled.", M,
                "Leave him at peace", "I left him at peace, for his hour had not yet come.", W),
            q("A raven watches from the apple tree.",
                "Answer its call", "I answered its call in its own voice, and it tilted its head.", W,
                "Feed it fruit", "I gave it a slice of apple from my own hand.", M,
                "Ask its name", "I asked its name; it gave me one I could not repeat.", X,
                "Leave it be", "I left it to its own errand, as the isle preferred.", W),
            q("The sisters offer you a cup that 'heals or changes.'",
                "Drink", "I drank; the cup was cold and tasted of summer.", C,
                "Refuse", "I refused; I had not come to be remade.", W,
                "Save it for another", "I saved the cup for my sister, who needed it more.", M,
                "Pour half to the ground", "I poured half to the ground for those the earth held.", M),
            q("An old wound of yours begins to ache.",
                "Name the wound aloud", "I named the wound aloud, so the isle could tend it.", M,
                "Ignore the ache", "I ignored the ache; I had carried it this long.", C,
                "Ask the sisters to ease it", "I asked the sisters, quietly, to ease the ache an hour.", M,
                "Thank it for its teaching", "I thanked the wound, briefly, and walked on.", W),
            q("Morgan asks what you will give for the cure.",
                "A year of my strength", "I offered a year of my strength for the cure.", C,
                "A name from my house", "I offered a name from my house; she would not take it.", X,
                "My first memory", "I offered my first memory of my mother's voice.", M,
                "My last fear", "I offered my last fear, which I did not need.", W),
            q("The mist returns, carrying the boat.",
                "Step aboard without looking back", "I stepped aboard without looking back at the orchard.", W,
                "Look once at the king", "I looked once at the king's chamber and remembered.", M,
                "Whisper a farewell to the sisters", "I whispered a farewell each of them must have heard.", M,
                "Gather an apple at my feet", "I gathered a fallen apple, which had no mark.", X),
            q("At the shore, the boatwoman lets you go.",
                "Pay her twice", "I paid her twice, so the next arrival could come freely.", M,
                "Bow in silence", "I bowed in silence and held her eyes a moment.", M,
                "Ask her name", "I asked her name; she smiled as if I had asked the tide.", X,
                "Promise to return", "I promised to return, and we both knew the shape of that promise.", W),
        )
    )

    private val troy = QuizChapter(
        chapterId = "troy",
        title = "The Fire of Troy",
        subtitle = "The last night of Ilion",
        realm = "Hellas",
        accent = MythColors.Crimson,
        opening = "The wooden horse stands in the agora, gifted and hollow. I hear the bolts slide inside it before anyone else, because I have been awake for three nights watching it.",
        closing = "Dawn comes pink through smoke. I am outside the walls now, a child in one arm and a sword I had never used before balanced against my hip. I keep walking.",
        questions = listOf(
            q("Cassandra runs past you, weeping warnings.",
                "Follow her", "I followed her, for she had never yet been wrong.", W,
                "Calm her aloud", "I spoke calmly to her, though I believed her already.", M,
                "Bar her path and ask", "I stopped her and asked what she had seen exactly.", X,
                "Ring the warning bell", "I rang the alarm bell on her word alone.", C),
            q("Priam's guards laugh at the bolted horse.",
                "Warn them again", "I warned them once more, though they mocked me openly.", C,
                "Leave them be", "I left them to their cups; I had to move faster.", W,
                "Speak to the priest", "I spoke to the priest, who believed more than the guards did.", W,
                "Bar a side gate secretly", "I slipped away and barred one side gate with a log.", X),
            q("You find a family asleep against the temple wall.",
                "Wake them now", "I woke them gently and told them to move at once.", M,
                "Carry the youngest", "I carried the smallest child without asking.", M,
                "Leave provisions for them", "I left bread and a skin of water and ran on.", M,
                "Promise to return", "I promised to return for them and meant it.", M),
            q("The first Greek leaps from the horse.",
                "Take him down", "I took him down at the horse's foot, before he could shout.", C,
                "Shout the alarm", "I shouted the alarm and woke a quarter of the city.", C,
                "Run for the king", "I ran for Priam's gate with the news before the rest.", C,
                "Light the beacon", "I lit the beacon on the tower above the agora.", C),
            q("A captain asks whether to hold the palace or the gate.",
                "Hold the gate", "I said the gate; if it fell we lost everyone behind it.", C,
                "Hold the palace", "I said the palace; the royal line must survive the night.", C,
                "Split our forces", "I urged him to split us in half and hold both.", X,
                "Evacuate first", "I told him to evacuate the children first, then decide.", M),
            q("Hector's son Astyanax cries in a corner.",
                "Take him with you", "I took the boy, whose mother was nowhere to be found.", M,
                "Find his mother", "I searched three rooms before I found Andromache.", M,
                "Hide him in the altar", "I hid him beneath the altar and promised to return.", X,
                "Hand him to Aeneas", "I gave him to Aeneas, who was already leaving.", W),
            q("An old enemy falls at your feet, pleading.",
                "Spare him", "I spared him; this was not the night for that reckoning.", M,
                "Ask his surrender", "I accepted his surrender and bound his hands.", W,
                "Kill him quickly", "I ended it quickly, so we would not bleed each other all night.", C,
                "Ignore him", "I walked past without lowering my blade.", C),
            q("Aeneas beckons you toward the west gate.",
                "Follow him", "I followed Aeneas; he was already building a city in his head.", W,
                "Take a last look", "I took one last look at the temple as Aeneas led me away.", W,
                "Help him carry Anchises", "I helped lift Anchises onto his son's strong back.", M,
                "Refuse and return", "I refused the gate and ran back toward the noise.", C),
            q("The flames take the roof of the great hall.",
                "Save the household gods", "I ran for the household images and wrapped them in cloth.", M,
                "Break open the granary", "I cut the granary rope so the city had bread afterwards.", X,
                "Bring the young queen out", "I led the young queen out by a servant's corridor.", M,
                "Try to douse the worst", "I tried, uselessly, to fight the worst corner with water.", C),
            q("You reach the north gate and find it held by Trojans.",
                "Rally them", "I rallied them with a name they all knew.", C,
                "Ask for their wounded", "I asked who was wounded and began to carry them.", M,
                "Lead them out the west", "I led them instead to the west, where the way was still open.", W,
                "Take a bow from the ground", "I took a fallen bow and loosed arrows until my hands shook.", C),
            q("A Greek captain recognises you from earlier wars.",
                "Fight him", "I fought him, and we both knew our names.", C,
                "Appeal to old bonds", "I appealed to an older bond and his sword lowered.", M,
                "Deceive him", "I told him a lie he wanted to believe and ran past.", X,
                "Offer a truce of one hour", "I offered a truce of one hour for the children to pass.", M),
            q("At the crest of the ridge, you turn for the last time.",
                "Make a vow", "I vowed never to forget a single name of this city.", M,
                "Burn the memory into me", "I stood until my eyes stung and I could feel the shape of it.", W,
                "Pour dust on my head", "I poured dust on my head and walked on.", M,
                "Call my people onward", "I called my people onward, so no one stayed on that ridge.", C),
        )
    )

    private val chichen = QuizChapter(
        chapterId = "chichen",
        title = "Serpent on the Steps",
        subtitle = "Chichén Itzá",
        realm = "Mayab",
        accent = MythColors.CyanBright,
        opening = "It is equinox. The shadow of a serpent begins to slide down the pyramid toward my feet. The priest-king watches me watching it, and lifts one painted hand.",
        closing = "The shadow at last touches the jaguar carved at the base. I take one step and the crowd breathes out. I do not remember the climb down; only that I did not fall.",
        questions = listOf(
            q("The priest-king asks your offering.",
                "Jade from my father", "I set my father's jade upon the altar, as he had wished.", M,
                "Blood from my own hand", "I opened my palm and offered red upon the stone.", C,
                "A maize cake", "I offered a maize cake my mother had baked that morning.", M,
                "A question instead", "I offered a question, which surprised him and the stone.", X),
            q("A copal brazier is placed in your hands.",
                "Offer it to Chaac", "I raised the brazier to Chaac, who holds the rain back or lets it fall.", M,
                "Offer it to Kukulkan", "I offered the smoke to the plumed one on the steps.", M,
                "Turn four ways", "I turned the brazier to each of the four directions.", W,
                "Carry it up the pyramid", "I carried the brazier to the landing above the second terrace.", C),
            q("You are to play a short match at the ball court.",
                "Play the ritual round", "I played carefully, for it was a ritual, not a game.", W,
                "Play to win", "I played to win, because the gods respect winners.", C,
                "Let the other win honestly", "I let the priest's son win honestly, because he needed it.", M,
                "Score on my own hip", "I struck the stone ring with my hip and the crowd cheered.", C),
            q("A storm builds over the cenote.",
                "Walk to its edge", "I walked to the cenote's edge and felt the water pull at me.", C,
                "Offer silver to the well", "I dropped a silver piece I had carried a long way.", M,
                "Speak Chaac's oldest name", "I spoke the oldest name of Chaac, so it might listen.", W,
                "Lie down in the rain", "I lay on the flagstones and let the rain find me.", W),
            q("A captive is brought to the altar, head bowed.",
                "Ask his name", "I asked his name, which was not something the priest-king did.", M,
                "Speak in his favour", "I spoke for him, though I knew I had no right.", C,
                "Bow my head as he does", "I bowed with him, so he would not be alone.", M,
                "Offer my own pain instead", "I offered my own small pain instead of his large one.", M),
            q("The shadow-serpent has seven segments.",
                "Name each one", "I named the seven segments under my breath as they appeared.", W,
                "Count my breaths to match", "I counted my breaths to match the arc of the shadow.", W,
                "Sing the old song", "I sang the song of the plumed one under my breath.", M,
                "Wait in silence", "I waited in silence, as my grandfather had taught.", W),
            q("The priest-king asks you to read a glyph.",
                "Read it honestly", "I read the glyph plainly, admitting when I did not know.", W,
                "Read it richly", "I read it richly, drawing meaning from every mark.", W,
                "Ask help from the scribe", "I asked the old scribe beside him for the harder lines.", M,
                "Suggest a second reading", "I offered a second reading and left him to choose.", X),
            q("You are offered a drink of fermented cacao.",
                "Drink slowly", "I drank it slowly and let my head find the sky.", M,
                "Pour a libation first", "I poured a libation to the four directions before drinking.", M,
                "Refuse respectfully", "I refused respectfully; the climb needed my full self.", W,
                "Share with the runner", "I passed half the cup to the runner who had brought it.", M),
            q("A macaw lands on the altar.",
                "Pluck one feather gently", "I took one feather for my hair, as was the custom.", C,
                "Leave it untouched", "I left it untouched, which was also a custom.", W,
                "Feed it from my hand", "I fed it a piece of maize cake from my hand.", M,
                "Greet it in the old tongue", "I greeted it in the old tongue and it answered.", W),
            q("Clouds break. The sun strikes the jaguar altar.",
                "Climb to meet it", "I climbed the steps to stand in the light.", C,
                "Kneel before it", "I knelt at the foot of the altar and waited.", M,
                "Shield my eyes and listen", "I shielded my eyes and listened for the next word.", W,
                "Sing the priest's song", "I sang the priest's response under my breath.", M),
            q("Kukulkan is said to speak through the wind.",
                "Listen for a name", "I listened, and one name came to me, which I remembered.", W,
                "Answer him in turn", "I answered him in turn, which only a few dare.", C,
                "Make my petition aloud", "I made my petition aloud at the steps' top.", M,
                "Bow silently", "I bowed silently, as my people had for centuries.", W),
            q("The priest-king gestures: descend.",
                "Descend without looking back", "I descended without looking back, the step steady beneath me.", C,
                "Count the stairs aloud", "I counted each stair, under my breath, all three hundred.", W,
                "Pause on the middle landing", "I paused at the landing and looked out at the plain.", W,
                "Thank each priest I pass", "I thanked each priest as I passed, by name where I knew it.", M),
        )
    )

    private val pasargadae = QuizChapter(
        chapterId = "pasargadae",
        title = "Cyrus's Garden",
        subtitle = "The paradise of the King of Kings",
        realm = "Persis",
        accent = MythColors.GoldBright,
        opening = "Four quadrants of garden stretch from the six stone steps of the tomb. Water crosses the paths in thin channels. The old king's name is spoken by the leaves themselves.",
        closing = "I leave the garden by the southern path, carrying a handful of seeds I did not plant. I will plant them somewhere else, and the garden will remain four.",
        questions = listOf(
            q("The gardener offers you a cup of water.",
                "Drink with thanks", "I drank and praised the water of this kingdom.", M,
                "Ask the source", "I asked which spring it came from, so I could learn.", W,
                "Offer a libation first", "I poured a measure to the earth before drinking.", M,
                "Share it with the child", "I shared the cup with a child watching from the hedge.", M),
            q("Which quadrant will you enter first?",
                "The pomegranate grove", "I walked to the pomegranate grove; their red was patient.", M,
                "The cypress walk", "I walked the cypress walk, where shade grew tallest.", W,
                "The rose beds", "I chose the rose beds, for their scent held stories.", M,
                "The channel crossing", "I chose the channel crossing, where four paths became one.", X),
            q("An old caretaker kneels among weeds.",
                "Kneel beside her", "I knelt and worked beside her until my knees hurt.", M,
                "Ask her name", "I asked her name and used it until I left.", M,
                "Bring her water", "I brought her fresh water from the nearest channel.", M,
                "Offer her my coin", "I offered a coin; she laughed and planted it.", M),
            q("A poet from Shiraz sits composing beside the rose beds.",
                "Listen to the draft", "I listened to his draft and told him which line sang.", M,
                "Offer a better phrase", "I offered a better word for the one that limped.", X,
                "Leave him in peace", "I left him in peace; poems need silence.", W,
                "Ask him about Cyrus", "I asked him what he knew of Cyrus's youngest laugh.", M),
            q("You pass the stone tomb of Cyrus.",
                "Read the old inscription", "I read the inscription: 'O man, I am Cyrus.'", W,
                "Kneel on the sixth step", "I knelt on the sixth step and spoke my name.", M,
                "Leave a sprig of myrtle", "I laid a sprig of myrtle beneath the inscription.", M,
                "Ask him a living question", "I asked a question, as if he could still hear.", W),
            q("A tree has fallen across the central channel.",
                "Clear it with others", "I called passing workers and we cleared it together.", M,
                "Leave it for the gardener", "I left it where it was, for the gardener to command.", W,
                "Re-route the water", "I dug a small detour so the lower beds would still drink.", X,
                "Carve the old king's name", "I carved the old king's name into the bark before we cleared it.", M),
            q("A dusty traveller asks for a place to rest.",
                "Show him the cypress walk", "I showed him the cypress walk, where the stones were cool.", M,
                "Walk with him a while", "I walked with him a while, until his breath calmed.", M,
                "Bring him from the spring", "I fetched water from the spring for his face.", M,
                "Offer him my last bread", "I gave him the bread I had set aside for my own evening.", M),
            q("The fourfold channel is said to mirror the world.",
                "Study each arm", "I studied each arm of the channel; they differed by a hand's breadth.", W,
                "Walk each channel once", "I walked each of the four channels from end to end.", C,
                "Float an offering on one", "I floated a paper boat carrying my gratitude.", M,
                "Ask why it is four", "I asked the old gardener why it must be four, and she smiled.", W),
            q("A quiet group are rehearsing a hymn to Ahuramazda.",
                "Join their song", "I joined them for a verse and my voice did not shame them.", M,
                "Listen from the shade", "I listened from the shade and took their tune to memory.", W,
                "Offer a second verse", "I offered a second verse I had once heard in Bactria.", X,
                "Bow and continue", "I bowed and continued, so I would not interrupt them.", W),
            q("A jay drops a seed at your feet.",
                "Plant it here", "I planted the seed where it fell, since the jay had chosen.", M,
                "Carry it onward", "I pocketed the seed to plant elsewhere on my road.", X,
                "Offer it to the gardener", "I took it to the gardener, who smiled and named its species.", M,
                "Leave it uncovered", "I left it uncovered; a bird, I thought, would find it soon.", W),
            q("You are asked what Cyrus would plant.",
                "A cedar", "I answered cedar, for the long breath of his kingdom.", W,
                "A pomegranate", "I answered pomegranate, for its many chambered wisdom.", W,
                "A rose", "I answered rose, for he too knew scent outlives stone.", M,
                "An olive", "I answered olive, because peace is a fruit he understood.", M),
            q("At the garden gate, a child asks what you will remember.",
                "Its sound", "I told her the sound of channels was what I would keep.", W,
                "Its scent", "I told her the scent of the roses in early sun.", M,
                "Its order", "I told her the careful order of the four quadrants.", W,
                "Her question", "I told her her question, which I would carry onward.", M),
        )
    )

    private val stonehenge = QuizChapter(
        chapterId = "stonehenge",
        title = "Stones of Salisbury",
        subtitle = "Solstice night",
        realm = "Albion",
        accent = MythColors.Gold,
        opening = "I have walked under stars since sundown. The great stones stand where they have always stood, and the nine druids are waiting with the heel-stone between their feet.",
        closing = "The first light strikes the altar. The druids bow, and one hands me a small flint knife I will carry the rest of my days. I walk south with the sun warming my back.",
        questions = listOf(
            q("The eldest druid asks why you have come.",
                "To serve", "I said I had come to serve the sun's return.", M,
                "To learn", "I said I had come to learn what I had been avoiding.", W,
                "To prove myself", "I said I had come to be measured against the stones.", C,
                "To witness", "I said I had come simply to witness, if they allowed.", W),
            q("The first trial is fire.",
                "Step through the hot ring", "I stepped through the ring of flame, and my hem did not burn.", C,
                "Carry the torch the long way", "I carried the torch around the circle, naming each stone.", W,
                "Tend the brazier", "I tended the brazier without looking up for an hour.", M,
                "Light the furthest stone", "I ran to the furthest stone to light its cresset.", C),
            q("The second trial is water.",
                "Wade the River Avon", "I waded across the river in the dark, and did not fall.", C,
                "Carry water to the altar", "I carried water in cupped hands across the circle.", M,
                "Wash each stone base", "I knelt and washed the bases of three stones at random.", M,
                "Read the reflection", "I read the reflection of stars in the river, stone by stone.", W),
            q("The third trial is earth.",
                "Dig with bare hands", "I dug with bare hands until I found the first old bone.", C,
                "Plant a seed of rowan", "I planted a rowan seed at the sixth stone's foot.", M,
                "Name each buried king", "I named the kings I had been told were here.", W,
                "Lie on the turf awhile", "I lay on the turf and let the dew take me.", W),
            q("The fourth trial is sky.",
                "Climb a trilithon", "I climbed the trilithon and stood there until the stars shifted.", C,
                "Count each constellation", "I counted each constellation until the druid stopped me.", W,
                "Name my oldest star", "I named the oldest star I had ever learned, and bowed.", M,
                "Follow the meteor west", "I followed the fall of a meteor with only my eyes.", W),
            q("A child druid trips beside you.",
                "Catch him", "I caught him by the sleeve before he met stone.", M,
                "Ignore it", "I let him fall; a druid learns to rise.", W,
                "Teach him the sign", "I taught him the sign for balance in the old tongue.", W,
                "Carry his torch a while", "I carried his torch so he could breathe again.", M),
            q("Nine bluestones sing under a certain drumbeat.",
                "Find the right beat", "I hunted the beat until the nearest stone answered back.", W,
                "Play a beat of my own", "I played a beat of my own; three stones replied.", X,
                "Listen and record", "I sat in silence and learned the pattern I heard.", W,
                "Teach it to the apprentice", "I taught the apprentice the pattern I had just learned.", M),
            q("A crow circles thrice.",
                "Take its sign", "I took the crow's sign and turned to face the altar.", W,
                "Answer its call", "I answered its caw in its own voice, and it paused.", X,
                "Offer it a grain", "I placed a grain on the altar for it to find.", M,
                "Ignore it", "I ignored the crow; sometimes a bird is only a bird.", W),
            q("The druids debate whether to welcome a stranger.",
                "Speak for him", "I spoke for him, though I had never seen his face before.", M,
                "Ask him to swear", "I asked him to swear an oath, and he swore.", C,
                "Vouch my own name", "I put my own name against his, so he could enter.", C,
                "Listen silently", "I listened in silence, then bowed to the eldest's call.", W),
            q("An owl calls from the far wood.",
                "Walk toward the call", "I walked toward the call; they let me go, nodding.", C,
                "Answer in return", "I answered softly, so it would not be alone.", M,
                "Note the number of calls", "I counted its calls: seven, which I remembered.", W,
                "Pour a measure of mead", "I poured mead for the owl, which flew off unsurprised.", M),
            q("The eldest asks what you will do with this night.",
                "Hold it in my body", "I said I would hold it in my body for a long time.", C,
                "Tell it to my children", "I said I would tell my children its shape.", M,
                "Turn it to a song", "I said I would turn it to a song I had not yet written.", W,
                "Keep it silent", "I said I would keep it silent, and say nothing to anyone.", W),
            q("First light. Will you walk the circle once more?",
                "Walk deosil", "I walked the circle with the sun, three times, slowly.", M,
                "Walk widdershins once", "I walked once against the sun, a private gesture.", X,
                "Lay my cloak on the altar", "I laid my cloak on the altar for the child druid.", M,
                "Stand still and watch", "I stood and watched the light climb the nearest stone.", W),
        )
    )

    private val greatwall = QuizChapter(
        chapterId = "greatwall",
        title = "Dragon of the Wall",
        subtitle = "A watchtower night",
        realm = "Zhongguo",
        accent = MythColors.Crimson,
        opening = "I have the watch on the wall tonight. The steppe breathes below. Somewhere out in the grass, torches are moving, and I must decide what to do before my sergeant wakes.",
        closing = "Dawn paints the stone rose and grey. My beacon is lit. My name is on the watch-list. The horsemen have not yet reached us. I go to lie down and sleep until my hands stop shaking.",
        questions = listOf(
            q("The first torch appears, far out on the grass.",
                "Light the beacon at once", "I lit the beacon without waiting for orders.", C,
                "Count the torches first", "I waited and counted the torches until five was my number.", W,
                "Wake my sergeant", "I woke my sergeant; he trusted me and did not complain.", M,
                "Send a runner south", "I sent a runner south to the next tower immediately.", X),
            q("A comrade asks whether to ready the crossbows.",
                "Ready them now", "I told him to ready the crossbows and sling them quietly.", C,
                "Leave them for dawn", "I told him no; dawn light was our ally, not our enemy.", W,
                "Prepare half and rest", "I told him to prepare half and rest the other half.", X,
                "Call the bowyer", "I called the bowyer to check the strings by lantern.", W),
            q("You see a figure walking the wall toward you.",
                "Challenge him", "I challenged him in the proper phrase, loud and clear.", C,
                "Wait for the sign", "I waited for the counter-sign before answering.", W,
                "Step into shadow", "I stepped into shadow and watched him pass.", X,
                "Whistle three notes", "I whistled the three notes our company used.", X),
            q("A soldier's brother is missing from the lower watch.",
                "Look for him now", "I slipped down and looked for the missing brother at once.", M,
                "Send for a search", "I sent word for a slow search, no alarm.", W,
                "Log the absence", "I logged the absence honestly in the watch book.", W,
                "Cover for him quietly", "I covered for him for an hour, then wrote it down.", M),
            q("An old woman shepherding goats nears the wall.",
                "Offer her shelter", "I gave her shelter in the stair-well for the night.", M,
                "Send her home", "I sent her home with a warning about riders near.", M,
                "Question her gently", "I asked gentle questions; she had seen torches also.", X,
                "Give her my cloak", "I lent her my cloak; she refused politely and it warmed her.", M),
            q("Torchlight begins to resolve into horsemen.",
                "Count their line", "I counted eighteen riders, and passed the count downwall.", W,
                "Measure their distance", "I measured their distance by the roman marker stones.", W,
                "Signal the next tower", "I signalled the next tower with our lantern code.", X,
                "Ready a horn", "I set the horn where my hand would find it in the dark.", C),
            q("Meng Tian's old tale is told to the recruits below.",
                "Let the telling continue", "I let the story be told; soldiers need their old ghosts.", M,
                "Join the telling", "I joined the telling with a variation my grandfather knew.", W,
                "Correct a detail", "I corrected one detail softly; the teller nodded.", W,
                "Hush the recruits", "I hushed them; the watch cannot be a story hour.", C),
            q("A riderless horse approaches the wall.",
                "Lower a rope", "I lowered a rope and brought the horse up by main strength.", M,
                "Let it pass", "I let the horse find its own way along the wall.", W,
                "Search the steppe", "I searched the steppe with my glass for its fallen rider.", X,
                "Call the healer", "I called the healer to come up in case a rider followed.", M),
            q("The signal from the next tower is unclear.",
                "Send for clarification", "I sent a rider to ask what they had seen exactly.", X,
                "Repeat our own signal", "I repeated our signal at full brightness.", C,
                "Light the second beacon", "I lit the second beacon; better wasteful than wrong.", C,
                "Consult the code-book", "I consulted the code-book in lamp-light to be certain.", W),
            q("A young soldier asks if he will live.",
                "Tell him yes", "I told him yes, and took his hand until it stopped shaking.", M,
                "Tell him the truth", "I told him we would do all we could, which was true.", W,
                "Change the subject", "I asked him the name of his mother's dog, and he laughed.", M,
                "Teach him a breathing", "I taught him the slow breath my own sergeant had once given me.", M),
            q("The horsemen turn east, and the threat slackens.",
                "Send a rider after them", "I sent a rider to follow at a distance and report.", X,
                "Hold the watch steady", "I held the watch steady; I had been wrong before.", W,
                "Thank the tower spirits", "I thanked the tower spirits, as my grandmother had taught.", M,
                "Grant half the watch rest", "I granted half the watch a short rest under cloaks.", M),
            q("Sunrise: you write the night's report.",
                "Make it exact", "I made the report exact, including my own mistakes.", W,
                "Include the soldier's name", "I named the young soldier for his steadiness.", M,
                "Note the torches turned east", "I noted carefully the direction of the torches at dawn.", W,
                "Keep one page for myself", "I kept one page for myself, for later, where I would write honestly.", W),
        )
    )

    private val babylon = QuizChapter(
        chapterId = "babylon",
        title = "Writing on the Wall",
        subtitle = "Belshazzar's last feast",
        realm = "Shinar",
        accent = MythColors.Azure,
        opening = "The hall is loud with wine and the king is toasting the gold his grandfather took from Jerusalem. A hand appears where no hand should be, and begins to write.",
        closing = "Outside, the city's water level has fallen a handbreadth. Cyrus's engineers are close enough that I can hear their horses. I slip the clay tablet into my sleeve and walk toward the quiet river gate.",
        questions = listOf(
            q("The king asks who will read the fiery words.",
                "Volunteer quietly", "I stepped forward quietly, since no one else would.", C,
                "Send for Daniel", "I sent at once for the prophet in the lower city.", W,
                "Study the writing first", "I studied the writing; three words, neither king's tongue.", W,
                "Stand aside", "I stood aside; this was not my hour to read.", W),
            q("Belshazzar offers you a purple robe for the reading.",
                "Accept with dignity", "I accepted with dignity; the robe did not flatter me.", M,
                "Refuse politely", "I refused politely; the words were payment enough.", W,
                "Give it to the scribe", "I gave it to the old scribe beside me.", M,
                "Ask for a second robe", "I asked a second for the servant who had lit the lamp.", M),
            q("The nobles of the court turn their eyes on you.",
                "Meet each eye", "I met each eye and nodded slowly as I passed.", C,
                "Keep mine on the script", "I kept my eyes on the script and did not falter.", W,
                "Find an ally", "I searched for one friendly face and found two.", X,
                "Speak only to the king", "I fixed my voice upon the king alone.", C),
            q("The three words resolve: Mene, Tekel, Upharsin.",
                "Translate each word", "I translated: numbered, weighed, divided.", W,
                "Say them softly at first", "I said them softly at first, then clearly.", W,
                "Ask the queen's counsel", "I asked the queen, who had read prophecies before.", M,
                "Write them on a tablet", "I wrote them on a tablet before I spoke them aloud.", W),
            q("The king's face is grey. Will you soften your reading?",
                "Give it straight", "I gave it straight; there was no mercy in softening.", C,
                "Couch it in older words", "I used older words, so the truth would land slower.", X,
                "Begin with the kinder part", "I began with the kinder part, so he could listen.", M,
                "Add a possible remedy", "I added that repentance had turned such verdicts before.", M),
            q("The queen rises and speaks for Daniel.",
                "Yield to Daniel", "I yielded; Daniel was the better reader, the older soul.", M,
                "Stay and support", "I stayed and stood behind him, for his voice alone was not enough.", M,
                "Ask her counsel aside", "I asked her counsel aside; she had seen this before.", W,
                "Bow and withdraw", "I bowed and withdrew to the pillars to listen.", W),
            q("A servant slips a warning to you about guards at the gates.",
                "Heed the warning", "I heeded the warning and began to plan a quiet exit.", X,
                "Warn the queen", "I passed the warning to the queen, who had children to save.", M,
                "Stay loyal to the king", "I stayed; loyalty is not measured in easy hours.", C,
                "Take the servant with me", "I told the servant to come with me, and she did.", M),
            q("The Euphrates sounds different tonight.",
                "Listen longer", "I listened; the water was lower than any season I knew.", W,
                "Ask a river-man", "I asked a river-man what he could hear, and he paled.", X,
                "Walk to the embankment", "I slipped to the embankment and saw stones dry-exposed.", C,
                "Send a rider east", "I sent a rider east, though my horses were the king's.", X),
            q("An old kinsman begs you to flee with him.",
                "Flee together", "I fled with him through the river gate, quietly.", C,
                "Send him on alone", "I sent him on; I had one last thing to do.", W,
                "Wait with him an hour", "I stayed with him one hour, so he was not alone.", M,
                "Hide him in the queen's wing", "I hid him in the queen's wing, where few dared search.", X),
            q("Cyrus's water-engineers are already in the river bed.",
                "Warn the gate captain", "I warned the gate captain, who trusted my face.", M,
                "Race to the palace", "I raced back to the palace to warn the king once more.", C,
                "Take a ferry to the east", "I bought a ferry to the east before the water turned.", X,
                "Light a lantern on the wall", "I lit a lantern on the wall — a sign for those we loved.", M),
            q("A child is lost in the press of fleeing servants.",
                "Lift her to my shoulder", "I lifted her to my shoulder and kept walking.", M,
                "Ask her name", "I asked her name and repeated it until she calmed.", M,
                "Carry her to the queen", "I carried her to the queen's wing, which was safer.", M,
                "Find her mother", "I looked for her mother, and did not give up.", M),
            q("At the river gate, a soldier asks what you carry.",
                "Tell him the truth", "I told him honestly; he let me through without a word.", C,
                "Show him my seal", "I showed the seal of the queen and he stepped aside.", X,
                "Offer a coin", "I offered a coin, not as a bribe but for his mother.", M,
                "Sing the old watch-song", "I sang the watch-song of our guild; he joined for a verse.", M),
        )
    )

    private val cumae = QuizChapter(
        chapterId = "cumae",
        title = "The Sibyl's Leaves",
        subtitle = "The gallery at Cumae",
        realm = "Latium",
        accent = MythColors.Emerald,
        opening = "The gallery at Cumae is long and cool, and the wind has already begun scattering the leaves the sibyl has written on. I crouch to gather what I can before they leave the cave.",
        closing = "She looks at me, the Sibyl, and her eyes are older than any city I have ever known. I rise from the leaves and step out into the harsh afternoon. The road to Rome is still long.",
        questions = listOf(
            q("The first leaf you read is blank.",
                "Turn it over", "I turned the leaf over; the other side bore one word.", W,
                "Set it carefully aside", "I set it aside; even empty leaves are a kind of answer.", W,
                "Ask the sibyl why", "I asked the Sibyl why, and she smiled a small smile.", X,
                "Write upon it myself", "I wrote upon it myself, a small phrase I had been holding.", C),
            q("The wind rises again and a dozen leaves spin past.",
                "Chase them", "I chased them down the tunnel, two at a time.", C,
                "Let them go", "I let them go; whoever needs those lines will find them.", W,
                "Mark where each landed", "I marked with chalk where each fell.", X,
                "Bring three to the Sibyl", "I brought three back to the Sibyl, and she nodded.", M),
            q("A leaf bears a name you did not expect.",
                "Speak it aloud", "I spoke the name aloud, and the cave grew colder.", C,
                "Hide it at my breast", "I hid the name at my breast and kept reading.", X,
                "Ask who it is", "I asked the Sibyl whose name it was.", W,
                "Copy it onto wax", "I copied the name onto my tablet of wax, just in case.", W),
            q("Aeneas's own hand is said to have left a mark here.",
                "Search the wall", "I searched the wall and found a line of soot-script.", W,
                "Ask for the story", "I asked the Sibyl to tell me what Aeneas had asked.", W,
                "Leave my mark beside his", "I left my own mark quietly beside his.", C,
                "Study the air where he stood", "I breathed the air where he once stood and felt a steadiness.", W),
            q("A Roman senator's messenger arrives with a question.",
                "Let him pass", "I stood aside so he could reach the Sibyl first.", M,
                "Ask his question also", "I asked his question too, so I could carry the answer.", X,
                "Carry his question for him", "I took his question and delivered it word for word.", M,
                "Refuse his coin", "I refused the coin he pressed upon me.", W),
            q("A leaf rolls to your feet with your own name.",
                "Read it alone", "I read it alone and did not share it.", W,
                "Show it to the Sibyl", "I showed it to the Sibyl, who had written it without knowing.", M,
                "Read only the verb", "I read only the verb and did not bother with the outcome.", W,
                "Set it back where it fell", "I set the leaf back exactly where I found it.", W),
            q("You find the leaf that reads: 'Rome shall burn.'",
                "Carry it north", "I carried it north to a senator who might act.", C,
                "Hide it away", "I hid the leaf where no mortal would find it.", X,
                "Ask when", "I asked the Sibyl when, and she showed me four fingers.", W,
                "Rewrite it softer", "I rewrote the leaf softer; the stone would judge me.", X),
            q("The Sibyl offers you her cup.",
                "Drink a little", "I drank a little and my sight trembled for one heartbeat.", C,
                "Refuse politely", "I refused politely; I had come to read, not to see.", W,
                "Pour some on the altar", "I poured half on the altar for those who could not.", M,
                "Share with my companion", "I shared the cup with my companion at the threshold.", M),
            q("A young woman arrives weeping.",
                "Sit with her", "I sat with her until the shaking went out of her hands.", M,
                "Ask the Sibyl's mercy", "I asked the Sibyl for mercy on her behalf.", M,
                "Read her a gentler leaf", "I found her a gentler leaf among those scattered.", M,
                "Walk her out", "I walked her out into the sun, which the Sibyl approved.", M),
            q("The old caretaker shows you the order of the books.",
                "Memorise the order", "I memorised the order; books are orphaned when their order is lost.", W,
                "Offer to record the order", "I offered to record the order in my own careful hand.", W,
                "Question a placement", "I questioned one placement, gently, and was corrected gently.", X,
                "Thank him without words", "I thanked him without words, by kneeling a moment.", M),
            q("The Sibyl asks: what will you tell them?",
                "The plainest truth", "I said I would tell them the plainest truth I had found.", C,
                "What they can bear", "I said I would tell them only what they could bear.", M,
                "Only what I know", "I said I would tell them only what I had seen myself.", W,
                "A story, not a prophecy", "I said I would make a story of it, and let them find prophecy.", W),
            q("You step back into the harsh sunlight.",
                "Walk to Rome at once", "I turned my horse for Rome without stopping at an inn.", C,
                "Write the leaves down", "I stopped at the first olive grove and wrote the leaves down.", W,
                "Eat first", "I ate first; the prophecy would keep another hour.", M,
                "Pray in the nearest shrine", "I prayed in the nearest shrine for the road I had chosen.", M),
        )
    )

    val chapters = listOf(delphi, hades, bifrost, osiris, avalon, troy, chichen, pasargadae, stonehenge, greatwall, babylon, cumae)

    fun byId(id: String): QuizChapter? = chapters.firstOrNull { it.chapterId == id }
}
