package org.example.project.screens.world

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import org.example.project.theme.MythColors

enum class MapStyle { Hellas, Kemet, Skandia, Albion, Persis, Shinar, Zhongguo, Mayab, Latium }

enum class PlaceType(val glyph: String, val label: String) {
    City("◉", "City"),
    Sanctuary("✦", "Sanctuary"),
    Temple("☗", "Temple"),
    Mountain("▲", "Peak"),
    Battle("⚔", "Battle"),
    Isle("❖", "Isle"),
}

data class PlaceStat(val label: String, val value: String)

data class HistoricCharacter(
    val id: String,
    val name: String,
    val role: String,
    val glyph: String,
    val accent: Color,
    val epithet: String,
    val might: Int,
    val wisdom: Int,
    val renown: Int,
    val cunning: Int,
    val divinity: Int,
) {
    val total: Int get() = might + wisdom + renown + cunning + divinity
}

data class HistoricPlace(
    val id: String,
    val name: String,
    val type: PlaceType,
    val relPos: Offset,
    val era: String,
    val synopsis: String,
    val story: String,
    val accent: Color,
    val stats: List<PlaceStat>,
    val characters: List<HistoricCharacter>,
)

data class AncientRealm(
    val id: String,
    val name: String,
    val tagline: String,
    val era: String,
    val accent: Color,
    val mapStyle: MapStyle,
    val places: List<HistoricPlace>,
)

// --- Character constructors (short aliases) ---
private fun hc(
    id: String, name: String, role: String, glyph: String, accent: Color, epithet: String,
    might: Int, wisdom: Int, renown: Int, cunning: Int, divinity: Int,
) = HistoricCharacter(id, name, role, glyph, accent, epithet, might, wisdom, renown, cunning, divinity)

object WorldCatalog {
    val realms: List<AncientRealm> = listOf(
        AncientRealm(
            id = "hellas",
            name = "Hellas",
            tagline = "Cradle of Olympian dawn",
            era = "c. 1200 – 146 BC",
            accent = MythColors.CyanBright,
            mapStyle = MapStyle.Hellas,
            places = listOf(
                HistoricPlace(
                    id = "olympus",
                    name = "Mount Olympus",
                    type = PlaceType.Mountain,
                    relPos = Offset(0.46f, 0.22f),
                    era = "Ages untold",
                    synopsis = "Throne of the Twelve.",
                    story = "On the ash-grey summit above the clouds, the Olympians held their council. Lightning crowned the peak; the dawn broke each morning upon the marble of the gods' hall. Mortal climbers who strayed too near were turned back by sudden storms, or lost in fog so white it blinded the eye. The Muses danced on the lower slopes, and from the spring of Pieria flowed the water that touched a poet's tongue.",
                    accent = MythColors.CyanBright,
                    stats = listOf(
                        PlaceStat("Height", "2917 m"),
                        PlaceStat("Gods enthroned", "12"),
                        PlaceStat("Ridges", "52"),
                        PlaceStat("First ascent", "1913 AD"),
                        PlaceStat("Recorded myths", "214"),
                        PlaceStat("Sacred springs", "3"),
                    ),
                    characters = listOf(
                        hc("zeus", "Zeus", "Lord of storms", "⚡", MythColors.Gold, "Cloud-gatherer", 98, 85, 100, 90, 100),
                        hc("hera", "Hera", "Queen of heavens", "☉", MythColors.GoldBright, "Ox-eyed queen", 82, 88, 97, 90, 99),
                        hc("apollo", "Apollo", "Oracle of light", "☀", MythColors.Sky, "Far-shooter", 90, 97, 99, 80, 100),
                    ),
                ),
                HistoricPlace(
                    id = "delphi",
                    name = "Delphi",
                    type = PlaceType.Sanctuary,
                    relPos = Offset(0.36f, 0.40f),
                    era = "c. 800 BC",
                    synopsis = "Navel of the world.",
                    story = "Where the Pythia breathed the vapours of the god and spoke in riddles that decided the fate of empires. Kings and heroes came seeking truth, and left with more questions than they brought. The stone navel marked the centre of the world, placed between the wings of two eagles Zeus sent from the ends of the earth. 'Know thyself' was carved above the temple door — an oracle more precise than any the priestess ever gave.",
                    accent = MythColors.Gold,
                    stats = listOf(
                        PlaceStat("Oracles recorded", "1100+"),
                        PlaceStat("Active years", "1100"),
                        PlaceStat("Pilgrims / yr", "30k"),
                        PlaceStat("Standing cols.", "6"),
                        PlaceStat("Treasuries", "20"),
                        PlaceStat("Sacred way steps", "850"),
                    ),
                    characters = listOf(
                        hc("pythia", "Pythia", "Seer of Apollo", "☽", MythColors.Gold, "Voice of Apollo", 30, 96, 88, 70, 82),
                        hc("croesus", "Croesus", "Lydian king", "◈", MythColors.GoldBright, "Wealthy sovereign", 55, 72, 84, 60, 15),
                        hc("orestes", "Orestes", "Cursed prince", "⚔", MythColors.Crimson, "Avenger of blood", 80, 55, 66, 45, 20),
                    ),
                ),
                HistoricPlace(
                    id = "athens",
                    name = "Athens",
                    type = PlaceType.City,
                    relPos = Offset(0.58f, 0.58f),
                    era = "c. 500 BC",
                    synopsis = "City of the violet crown.",
                    story = "Beneath the Parthenon the first democracy was born. Philosophers, poets, and sculptors shaped a civilisation whose voice still carries across two and a half millennia. Here Pericles gave his funeral oration and Phidias raised Athena in ivory and gold. The Academy and Lyceum opened their gates to free men, while slaves ground olives in the silence beyond. When the Persians burned the city twice, the Athenians rebuilt it taller; when the plague came, they wrote it down.",
                    accent = MythColors.Sky,
                    stats = listOf(
                        PlaceStat("Golden age", "480–404 BC"),
                        PlaceStat("Agora area", "40k m²"),
                        PlaceStat("Dramas staged", "1k+"),
                        PlaceStat("Assembly seats", "6000"),
                        PlaceStat("Citizens", "40k"),
                        PlaceStat("Marble (Pent.)", "25k t"),
                    ),
                    characters = listOf(
                        hc("athena", "Athena", "Patron goddess", "✦", MythColors.CyanBright, "Grey-eyed", 90, 99, 99, 95, 100),
                        hc("pericles", "Pericles", "Statesman", "◉", MythColors.Sky, "Olympian orator", 72, 94, 95, 90, 8),
                        hc("socrates", "Socrates", "The gadfly", "☯", MythColors.Gold, "Father of inquiry", 40, 100, 92, 98, 12),
                    ),
                ),
                HistoricPlace(
                    id = "troy",
                    name = "Troy",
                    type = PlaceType.Battle,
                    relPos = Offset(0.82f, 0.30f),
                    era = "c. 1200 BC",
                    synopsis = "Where heroes fell for a queen.",
                    story = "For ten years the walls held against the Achaean ships, until a wooden horse carried war into the sleeping city. The Iliad still sings the rage of Achilles and the grief of Priam. Heinrich Schliemann believed enough to dig, and found city upon city — nine Troys stacked like stories in an old book. Beneath them, a fragment of gold remembered Helen. The dust of Hisarlik gave up its bones to a schoolboy's dream.",
                    accent = MythColors.Crimson,
                    stats = listOf(
                        PlaceStat("Siege years", "10"),
                        PlaceStat("Heroes slain", "44"),
                        PlaceStat("Wall layers", "9"),
                        PlaceStat("Combined age", "3500 yrs"),
                        PlaceStat("Gold fragments", "8750"),
                        PlaceStat("Citadel area", "2 ha"),
                    ),
                    characters = listOf(
                        hc("achilles", "Achilles", "Peleus' wrath", "⚔", MythColors.Crimson, "Swift-footed", 100, 60, 99, 55, 75),
                        hc("hector", "Hector", "Troy's shield", "◈", MythColors.Cyan, "Tamer of horses", 94, 82, 94, 72, 20),
                        hc("helen", "Helen", "The kindled fire", "♡", MythColors.GoldBright, "Bright of face", 30, 70, 100, 75, 50),
                    ),
                ),
                HistoricPlace(
                    id = "crete",
                    name = "Knossos",
                    type = PlaceType.Isle,
                    relPos = Offset(0.58f, 0.86f),
                    era = "c. 1900 BC",
                    synopsis = "Labyrinth of the bull-king.",
                    story = "Below the painted halls of Minos wound the labyrinth, where the Minotaur paced. Theseus, with a thread of Ariadne, walked its coils and returned into legend. The frescoes showed slender dancers leaping over bulls, the bright undersea of the Aegean, a court free of war. Then in one afternoon, an earthquake and a wave from Thera sent the Minoan age into myth. Arthur Evans found it beneath twenty feet of ash and taught a forgotten age to read its own walls.",
                    accent = MythColors.Emerald,
                    stats = listOf(
                        PlaceStat("Palace rooms", "1300"),
                        PlaceStat("Bull frescoes", "27"),
                        PlaceStat("Script", "Linear A"),
                        PlaceStat("Palace area", "20k m²"),
                        PlaceStat("Storerooms", "18"),
                        PlaceStat("Collapse", "c. 1450 BC"),
                    ),
                    characters = listOf(
                        hc("minos", "Minos", "Thalassocrat", "♜", MythColors.Gold, "Lawgiver of Crete", 70, 82, 88, 75, 55),
                        hc("theseus", "Theseus", "Thread-walker", "⚔", MythColors.CyanBright, "Slayer of the bull", 92, 72, 90, 80, 55),
                        hc("ariadne", "Ariadne", "The guide", "✧", MythColors.Sky, "Thread-holder", 45, 80, 72, 90, 55),
                    ),
                ),
            ),
        ),
        AncientRealm(
            id = "kemet",
            name = "Kemet",
            tagline = "The black land along the river",
            era = "c. 3100 – 30 BC",
            accent = MythColors.Gold,
            mapStyle = MapStyle.Kemet,
            places = listOf(
                HistoricPlace(
                    id = "giza",
                    name = "Giza Plateau",
                    type = PlaceType.Temple,
                    relPos = Offset(0.38f, 0.18f),
                    era = "c. 2560 BC",
                    synopsis = "Stairway of kings.",
                    story = "Three pyramids align with the stars of Orion's belt, guarded by the lion-bodied Sphinx. Khufu's tomb remains the greatest stone monument ever raised by hand. Twenty years of work by tens of thousands of men, hauling limestone from Tura and granite from Aswan. The pyramid once shone like a mirror — its casing white, its capstone plated with electrum. When Napoleon's savants stood at its foot, they calculated there was stone enough to wall all France.",
                    accent = MythColors.GoldBright,
                    stats = listOf(
                        PlaceStat("Great Pyramid", "146 m"),
                        PlaceStat("Stone blocks", "2.3 M"),
                        PlaceStat("Sphinx length", "73 m"),
                        PlaceStat("Workers", "20k"),
                        PlaceStat("Build years", "23"),
                        PlaceStat("Casing weight", "40k t"),
                    ),
                    characters = listOf(
                        hc("khufu", "Khufu", "Builder-king", "☥", MythColors.Gold, "Pyramid-raiser", 70, 78, 96, 82, 80),
                        hc("hemiunu", "Hemiunu", "Master architect", "◈", MythColors.GoldBright, "Stone-mover", 45, 96, 70, 90, 30),
                        hc("anubis", "Anubis", "Jackal guardian", "☽", MythColors.Azure, "Guardian of the scale", 60, 78, 80, 80, 100),
                    ),
                ),
                HistoricPlace(
                    id = "thebes",
                    name = "Thebes",
                    type = PlaceType.City,
                    relPos = Offset(0.56f, 0.56f),
                    era = "c. 2000 BC",
                    synopsis = "City of a hundred gates.",
                    story = "Capital of the New Kingdom, ruled by pharaohs whose funerary temples still rise beside the Nile. Here Amun-Ra was crowned king of gods. In the Valley of the Kings across the river, tombs were hewn so deep that their walls still hold the colours they were painted in. Hatshepsut's obelisks scraped the sky, and Ramses' monuments declared the king a god thrice over. Homer called it the city of a hundred gates — and a hundred more of gold behind each.",
                    accent = MythColors.Gold,
                    stats = listOf(
                        PlaceStat("Gates (Homer)", "100"),
                        PlaceStat("Tombs (V. of K.)", "63"),
                        PlaceStat("Priests", "4000"),
                        PlaceStat("Obelisks", "18"),
                        PlaceStat("Named dynasties", "11"),
                        PlaceStat("Flood cycles", "1500+"),
                    ),
                    characters = listOf(
                        hc("hatshepsut", "Hatshepsut", "Female pharaoh", "☥", MythColors.GoldBright, "King's daughter", 70, 88, 90, 88, 80),
                        hc("ramesses", "Ramesses II", "The Great", "☀", MythColors.Gold, "Sun of sovereigns", 95, 84, 98, 78, 92),
                        hc("amunra", "Amun-Ra", "Sun-king of gods", "◉", MythColors.Crimson, "Hidden sun", 90, 92, 98, 88, 100),
                    ),
                ),
                HistoricPlace(
                    id = "karnak",
                    name = "Karnak",
                    type = PlaceType.Sanctuary,
                    relPos = Offset(0.46f, 0.40f),
                    era = "c. 2055 BC",
                    synopsis = "Forest of stone columns.",
                    story = "The hypostyle hall rises like a papyrus marsh turned to stone — 134 columns taller than trees, carved with the deeds of kings and the names of gods. Every pharaoh added a pylon, an avenue, a shrine. For two thousand years masons never stopped working, and the site grew into a stone forest larger than any cathedral ever built. Ram-headed sphinxes still line the processional way that once joined Karnak to Luxor, three kilometres of stone staring down the sun.",
                    accent = MythColors.Sky,
                    stats = listOf(
                        PlaceStat("Columns", "134"),
                        PlaceStat("Great hall", "5000 m²"),
                        PlaceStat("Dynasties", "30+"),
                        PlaceStat("Pylons", "10"),
                        PlaceStat("Sacred lake", "2400 m²"),
                        PlaceStat("Avenue sphinxes", "1350"),
                    ),
                    characters = listOf(
                        hc("seti", "Seti I", "Builder pharaoh", "◈", MythColors.Gold, "Son of Set", 88, 86, 86, 72, 80),
                        hc("imhotep", "Imhotep", "Scribe of stone", "✦", MythColors.CyanBright, "Mover of stones", 45, 97, 86, 92, 78),
                        hc("mut", "Mut", "Mother goddess", "☽", MythColors.GoldBright, "Lady of heaven", 70, 82, 84, 80, 98),
                    ),
                ),
                HistoricPlace(
                    id = "abydos",
                    name = "Abydos",
                    type = PlaceType.Temple,
                    relPos = Offset(0.60f, 0.76f),
                    era = "c. 3100 BC",
                    synopsis = "Gate of the blessed dead.",
                    story = "Osiris was said to be buried here, and for thousands of years the faithful were brought to rest within sight of his mound, hoping for rebirth beside the lord of the afterlife. The Abydos king list records 76 pharaohs in a single stone — a genealogy for eternity. Seti I's temple carries the finest relief carving in all Egypt; lines so fine a hand could not cast a shadow on them. The poor who could not afford a pilgrim's grave bought a stela, buried it at the terrace, and hoped for the journey.",
                    accent = MythColors.Emerald,
                    stats = listOf(
                        PlaceStat("Royal tombs", "16"),
                        PlaceStat("Boat burials", "14"),
                        PlaceStat("Active years", "3000"),
                        PlaceStat("Kings listed", "76"),
                        PlaceStat("Relief carvings", "800+"),
                        PlaceStat("Pilgrim graves", "40k"),
                    ),
                    characters = listOf(
                        hc("osiris", "Osiris", "Lord of rebirth", "☥", MythColors.Emerald, "Lord of the west", 75, 90, 95, 80, 100),
                        hc("isis", "Isis", "Seeker wife", "◉", MythColors.Gold, "Giver of life", 70, 95, 95, 92, 100),
                        hc("horus", "Horus", "Falcon prince", "☼", MythColors.Sky, "Falcon on the horizon", 92, 82, 92, 85, 99),
                    ),
                ),
                HistoricPlace(
                    id = "alex",
                    name = "Alexandria",
                    type = PlaceType.City,
                    relPos = Offset(0.28f, 0.90f),
                    era = "331 BC",
                    synopsis = "Library of the world.",
                    story = "Founded by Alexander, lit by the Pharos, enriched by a library that held the learning of every people. The last flame of antiquity burned here before it dimmed. Ships entering the harbour saw the lighthouse from 50 km out, a bronze mirror reflecting the sun by day and a fire by night. Poets wrote of the city's Mouseion — a house of the Muses where scholars ate at the king's table in return for their pages. Here Euclid drew his geometry, Eratosthenes measured the earth, and Hypatia traced the motions of the stars until a mob cut her down.",
                    accent = MythColors.Azure,
                    stats = listOf(
                        PlaceStat("Scrolls", "700k"),
                        PlaceStat("Lighthouse", "100 m"),
                        PlaceStat("City quarters", "5"),
                        PlaceStat("Harbour ships", "1200"),
                        PlaceStat("Scholars kept", "100+"),
                        PlaceStat("Street grid", "14 × 11"),
                    ),
                    characters = listOf(
                        hc("alexander", "Alexander", "World-conqueror", "⚔", MythColors.Gold, "Two-horned", 99, 85, 100, 92, 65),
                        hc("cleopatra", "Cleopatra VII", "Last pharaoh", "☽", MythColors.GoldBright, "Star of the Nile", 55, 93, 97, 96, 70),
                        hc("hypatia", "Hypatia", "Mathematician", "✦", MythColors.CyanBright, "Star of scholarship", 25, 99, 88, 85, 15),
                    ),
                ),
            ),
        ),
        AncientRealm(
            id = "skandia",
            name = "Skandia",
            tagline = "Where the Bifrost burns",
            era = "c. 800 – 1100 AD",
            accent = MythColors.Sky,
            mapStyle = MapStyle.Skandia,
            places = listOf(
                HistoricPlace(
                    id = "asgard",
                    name = "Asgard",
                    type = PlaceType.Sanctuary,
                    relPos = Offset(0.54f, 0.16f),
                    era = "Beyond time",
                    synopsis = "Hall of the Aesir.",
                    story = "High above the worlds, Valhalla's gold roof gleams. Odin watches from Hlidskjalf; the Einherjar feast and wait for the day the serpent wakes. The bridge Bifrost is a trembling rainbow guarded by Heimdall, who hears the grass grow on both sides of the world. In the apple orchard of Idun the gods remain young, while beneath the roots of Yggdrasil the Norns weave the fate of every thread. When the horn Gjallarhorn is finally blown, the old worlds will drown and new ones rise from the sea.",
                    accent = MythColors.Gold,
                    stats = listOf(
                        PlaceStat("Halls", "12"),
                        PlaceStat("Einherjar", "∞"),
                        PlaceStat("Valhalla gates", "540"),
                        PlaceStat("Warriors / gate", "800"),
                        PlaceStat("Feasting benches", "9k"),
                        PlaceStat("Rivers to Bifrost", "11"),
                    ),
                    characters = listOf(
                        hc("odin", "Odin", "Allfather", "ᚠ", MythColors.Gold, "One-eyed wanderer", 94, 100, 98, 95, 99),
                        hc("thor", "Thor", "Storm-hammer", "⚡", MythColors.CyanBright, "Thunder-bearer", 100, 70, 96, 65, 96),
                        hc("freyja", "Freyja", "Lady of seiðr", "♡", MythColors.GoldBright, "Lady of falcon feathers", 72, 92, 92, 88, 96),
                    ),
                ),
                HistoricPlace(
                    id = "uppsala",
                    name = "Uppsala",
                    type = PlaceType.Temple,
                    relPos = Offset(0.62f, 0.46f),
                    era = "c. 800 AD",
                    synopsis = "Grove of the three gods.",
                    story = "Every ninth year, kings and farmers gathered for the great blót. Nine of every living thing were hung from the sacred grove as an offering to Odin, Thor, and Freyr. Adam of Bremen described a feast lasting nine nights, with the bodies swaying like dark fruit. Beneath the mounds of three royal burials, grave goods of gold and garnet still await the plough of a careful archaeologist. The old temple finally fell when the saint's word reached the north; its timbers built the church that stands in its place.",
                    accent = MythColors.Emerald,
                    stats = listOf(
                        PlaceStat("Ritual interval", "9 yrs"),
                        PlaceStat("Sacred trees", "9"),
                        PlaceStat("Royal burials", "3"),
                        PlaceStat("Temple gold", "7 t"),
                        PlaceStat("Feast duration", "9 nights"),
                        PlaceStat("Runic stones", "320"),
                    ),
                    characters = listOf(
                        hc("freyr", "Freyr", "Lord of harvest", "☼", MythColors.Emerald, "Of the golden boar", 70, 80, 80, 72, 92),
                        hc("adambr", "Adam of Bremen", "Chronicler", "◈", MythColors.Sky, "Northern chronicler", 20, 84, 58, 60, 12),
                        hc("aun", "King Aun", "Long-lived", "♛", MythColors.Gold, "Sacrifice of sons", 60, 60, 48, 55, 20),
                    ),
                ),
                HistoricPlace(
                    id = "hedeby",
                    name = "Hedeby",
                    type = PlaceType.City,
                    relPos = Offset(0.40f, 0.82f),
                    era = "c. 770 AD",
                    synopsis = "Harbour of the north.",
                    story = "The greatest trading city of the Viking age, where silver from Baghdad met amber from the Baltic and slaves from the Slavic east. A crossroads of the known world. Merchants stepped off longships onto board-walks, traded dirhams for soapstone, furs for Frankish swords. Ibn Fadlan, passing through as envoy of the caliph, wrote of the strange rites of the Rus with a mixture of horror and fascination. One summer a Norwegian king burned it to the waterline, and it was never rebuilt.",
                    accent = MythColors.CyanBright,
                    stats = listOf(
                        PlaceStat("Inhabitants", "1500"),
                        PlaceStat("Trade routes", "11"),
                        PlaceStat("Runestones", "34"),
                        PlaceStat("Harbour berths", "40"),
                        PlaceStat("Dirhams found", "1700"),
                        PlaceStat("Destroyed", "1066 AD"),
                    ),
                    characters = listOf(
                        hc("harald", "Harald I", "Bluetooth king", "ᛒ", MythColors.CyanBright, "Uniter of Danes", 82, 75, 80, 85, 18),
                        hc("ibnfadlan", "Ibn Fadlan", "Arab envoy", "✦", MythColors.Gold, "Traveller of the Caliph", 25, 86, 52, 72, 10),
                        hc("ragnar", "Ragnar", "Sea-raider", "⚔", MythColors.Crimson, "Hairy-breeches", 92, 70, 88, 78, 20),
                    ),
                ),
                HistoricPlace(
                    id = "jotun",
                    name = "Jötunheim",
                    type = PlaceType.Mountain,
                    relPos = Offset(0.74f, 0.62f),
                    era = "Primordial",
                    synopsis = "Frozen land of giants.",
                    story = "East across the Iving, where frost older than gods still walks. Thor's hammer has rung in these peaks, and Loki's kin rise to meet the final winter. Skadi strode on skis where no sun reached; Utgard-Loki tricked the thunder god with his riddles; Mimir's head, when drawn from the well, still murmured of paths only giants knew. Here too grew the tree Laeradr, whose fruit Idun kept; and the river Elivagar, whose ice formed the first giant from the first poison.",
                    accent = MythColors.Cyan,
                    stats = listOf(
                        PlaceStat("Peaks", "99"),
                        PlaceStat("Giant clans", "7"),
                        PlaceStat("Winter length", "∞"),
                        PlaceStat("Ivory wells", "3"),
                        PlaceStat("Frost age", "9 ages"),
                        PlaceStat("Brewing vats", "1"),
                    ),
                    characters = listOf(
                        hc("ymir", "Ymir", "Primal giant", "❄", MythColors.Cyan, "The first frost", 98, 60, 72, 45, 95),
                        hc("skadi", "Skadi", "Ski-huntress", "↟", MythColors.CyanBright, "Snow-shoe lady", 88, 72, 72, 75, 85),
                        hc("loki", "Loki", "Shape-walker", "✧", MythColors.Emerald, "Sky-treader", 70, 90, 85, 100, 88),
                    ),
                ),
            ),
        ),
        AncientRealm(
            id = "albion",
            name = "Albion",
            tagline = "Isle of mist and standing stones",
            era = "c. 3000 BC – 600 AD",
            accent = MythColors.Emerald,
            mapStyle = MapStyle.Albion,
            places = listOf(
                HistoricPlace(
                    id = "stonehenge",
                    name = "Stonehenge",
                    type = PlaceType.Sanctuary,
                    relPos = Offset(0.48f, 0.58f),
                    era = "c. 3000 BC",
                    synopsis = "Clock of the sun.",
                    story = "Raised on Salisbury Plain in an age before writing, the stones still catch the dawn of each solstice. No one knows who raised them, only that they watched the sky. The bluestones were carried 230 km from the Preseli hills of Wales — floated on the Severn, dragged over rollers, tilted into their sockets with ropes of sinew. Two thousand summers later they still stand to within a handbreadth of where they were placed. When the morning of midsummer breaks, the heel-stone casts its shadow into the ring; the dead buried around the circle outnumber the living who ever walked between its stones.",
                    accent = MythColors.Gold,
                    stats = listOf(
                        PlaceStat("Sarsen weight", "25 t"),
                        PlaceStat("Diameter", "33 m"),
                        PlaceStat("Alignment", "Solstice"),
                        PlaceStat("Stone count", "83"),
                        PlaceStat("Bluestone origin", "230 km"),
                        PlaceStat("Build duration", "1500 yrs"),
                    ),
                    characters = listOf(
                        hc("druid", "Druid Elder", "Keeper of rites", "☉", MythColors.Emerald, "Star-watcher", 45, 90, 60, 75, 55),
                        hc("merlin", "Merlin", "Legend-weaver", "✦", MythColors.Sky, "Wizard of Wales", 55, 100, 95, 98, 88),
                        hc("bluestone", "Bluestone Mason", "Welsh carrier", "◉", MythColors.CyanBright, "Stone-bearer", 62, 70, 30, 55, 10),
                    ),
                ),
                HistoricPlace(
                    id = "tintagel",
                    name = "Tintagel",
                    type = PlaceType.City,
                    relPos = Offset(0.28f, 0.74f),
                    era = "c. 500 AD",
                    synopsis = "Cradle of the once-king.",
                    story = "On a windswept headland the conception of Arthur was veiled in Merlin's magic. The sea caves below still echo with the tide that carried a kingdom into legend. Dark Age trade brought Byzantine wine amphorae to this edge of the world; a slate with the name 'Artognou' scratched into it was pulled from the rubble. The past, as ever in Albion, is half history and half rumour — and the mist that rolls up from the sea hides both from the uninvited eye.",
                    accent = MythColors.Crimson,
                    stats = listOf(
                        PlaceStat("Cliff height", "90 m"),
                        PlaceStat("Dark age occup.", "400 yrs"),
                        PlaceStat("Byz. finds", "200+"),
                        PlaceStat("Slate inscriptions", "6"),
                        PlaceStat("Tunnel length", "40 m"),
                        PlaceStat("Causeway depth", "18 m"),
                    ),
                    characters = listOf(
                        hc("uther", "Uther", "Pendragon", "⚔", MythColors.Crimson, "Chief of dragons", 88, 65, 70, 72, 35),
                        hc("igraine", "Igraine", "Lady of Cornwall", "♡", MythColors.GoldBright, "Mother of the king", 45, 75, 72, 70, 25),
                    ),
                ),
                HistoricPlace(
                    id = "avalon",
                    name = "Avalon",
                    type = PlaceType.Isle,
                    relPos = Offset(0.14f, 0.42f),
                    era = "Mythic",
                    synopsis = "Orchard of the apple-isle.",
                    story = "Where Arthur was carried after his last battle, and where he is said to sleep until Britain's darkest hour. The mist parts only for those summoned. Glastonbury Tor rises above the drained marshes that once made it an island, and beneath its chapel monks uncovered bones they swore were Arthur and Guinevere — a holy rediscovery that proved too convenient by half. Nine sisters of healing were said to keep the orchards, and their leader, Morgan, could bind a wound with a song.",
                    accent = MythColors.Emerald,
                    stats = listOf(
                        PlaceStat("Visible days", "Few"),
                        PlaceStat("Apple groves", "9"),
                        PlaceStat("Healing springs", "3"),
                        PlaceStat("Tor height", "159 m"),
                        PlaceStat("Refounding", "1191 AD"),
                        PlaceStat("Sisters of heal.", "9"),
                    ),
                    characters = listOf(
                        hc("morgan", "Morgan", "Fay-queen", "☽", MythColors.Emerald, "Mistress of healing", 70, 95, 80, 96, 80),
                        hc("ninesisters", "Nine Sisters", "Healers", "✦", MythColors.CyanBright, "Wardens of Avalon", 40, 92, 70, 82, 75),
                        hc("arthur", "Arthur", "The sleeper king", "♛", MythColors.Gold, "Once and future king", 94, 85, 100, 82, 55),
                    ),
                ),
                HistoricPlace(
                    id = "tara",
                    name = "Hill of Tara",
                    type = PlaceType.Temple,
                    relPos = Offset(0.62f, 0.26f),
                    era = "c. 2500 BC",
                    synopsis = "Seat of the high kings.",
                    story = "A mound that crowned 142 kings of Éire. The Lia Fáil stood here, singing out beneath the rightful ruler. Below the earth lies a passage older than the pyramids. Twice a year, at cross-quarter dawns, sun enters the passage tomb and walks down the corridor to the inner chamber. The high kings came, sat on a seat that faced the four provinces, and gave the law. In the bronze age, a man was buried here with gold moons on his breast and a chain of amber around his neck.",
                    accent = MythColors.GoldBright,
                    stats = listOf(
                        PlaceStat("High kings", "142"),
                        PlaceStat("Mound age", "5.5 k yrs"),
                        PlaceStat("Monuments", "30"),
                        PlaceStat("Passage length", "20 m"),
                        PlaceStat("Sun alignments", "2"),
                        PlaceStat("Provinces", "4"),
                    ),
                    characters = listOf(
                        hc("lugh", "Lugh", "Sun-bright", "☀", MythColors.Gold, "Long-handed", 92, 92, 94, 85, 98),
                        hc("medb", "Medb", "Warrior queen", "⚔", MythColors.Crimson, "Intoxicating one", 88, 78, 90, 88, 45),
                        hc("dagda", "Dagda", "Good god", "◈", MythColors.Emerald, "All-father of Éire", 90, 90, 90, 78, 96),
                    ),
                ),
            ),
        ),
        AncientRealm(
            id = "persis",
            name = "Persis",
            tagline = "Plateau of the King of Kings",
            era = "c. 550 – 330 BC",
            accent = MythColors.GoldBright,
            mapStyle = MapStyle.Persis,
            places = listOf(
                HistoricPlace(
                    id = "persepolis",
                    name = "Persepolis",
                    type = PlaceType.Sanctuary,
                    relPos = Offset(0.46f, 0.62f),
                    era = "c. 518 BC",
                    synopsis = "Throne of the Achaemenids.",
                    story = "Terraces carved from the living rock, bas-reliefs where every tributary of the empire brought gifts to the King of Kings. Alexander burned it in a night that ended a world. Darius raised the platform; Xerxes built the Gate of All Nations; the Treasury held tribute from India to Libya. When the Macedonian torches were thrown, it took days for the fire to stop. The heat was so fierce the mud-brick cores of the palaces fused like glass, and the wind carried soot as far as Susa.",
                    accent = MythColors.GoldBright,
                    stats = listOf(
                        PlaceStat("Terrace area", "125k m²"),
                        PlaceStat("Tribute nations", "23"),
                        PlaceStat("Apadana cols.", "72"),
                        PlaceStat("Tribute figures", "275"),
                        PlaceStat("Cuneiform tablets", "30k"),
                        PlaceStat("Burned", "330 BC"),
                    ),
                    characters = listOf(
                        hc("darius", "Darius I", "The Great", "♛", MythColors.Gold, "Truth-teller of Persia", 80, 92, 98, 90, 20),
                        hc("xerxes", "Xerxes", "King of kings", "◈", MythColors.GoldBright, "Chastiser of the sea", 82, 72, 94, 72, 20),
                        hc("parmenion", "Parmenion", "Macedon's blade", "⚔", MythColors.Crimson, "Old fox of Macedon", 90, 78, 85, 85, 8),
                    ),
                ),
                HistoricPlace(
                    id = "susa",
                    name = "Susa",
                    type = PlaceType.City,
                    relPos = Offset(0.22f, 0.42f),
                    era = "c. 4200 BC",
                    synopsis = "Winter seat of the Shahs.",
                    story = "Older than Babylon, home to Elamite kings and later capital of the Achaemenids. Here the Book of Esther places her queenship; here Daniel was said to have dreamed of rams and goats. Darius built a palace roofed in cedar and silver; archers in glazed brick paraded along its walls, ten thousand immortals stepping into eternity. The royal road ran from its gate to Sardis, a hundred and eleven stations, the swiftest couriers in the world changing horses at every one.",
                    accent = MythColors.Sky,
                    stats = listOf(
                        PlaceStat("Occupied", "4500 yrs"),
                        PlaceStat("Citadels", "3"),
                        PlaceStat("Royal archive", "50k tab."),
                        PlaceStat("Immortal frieze", "10k"),
                        PlaceStat("Royal road end", "Sardis"),
                        PlaceStat("Elamite layers", "12"),
                    ),
                    characters = listOf(
                        hc("cyrus", "Cyrus II", "Liberator", "☼", MythColors.Gold, "Father of Persia", 92, 94, 100, 92, 35),
                        hc("esther", "Esther", "Queen of stars", "✦", MythColors.GoldBright, "Saviour of a people", 40, 88, 80, 92, 35),
                        hc("daniel", "Daniel", "Dream-reader", "☽", MythColors.CyanBright, "Lion-walker", 30, 96, 80, 82, 72),
                    ),
                ),
                HistoricPlace(
                    id = "pasargadae",
                    name = "Pasargadae",
                    type = PlaceType.Temple,
                    relPos = Offset(0.58f, 0.46f),
                    era = "c. 546 BC",
                    synopsis = "Tomb of Cyrus.",
                    story = "A stone house on six steps where Cyrus the Great sleeps. Alexander, on seeing it plundered, wept and restored the inscription: 'O man, whosoever thou art, I am Cyrus.' The Chahar Bagh garden was the first of its kind — four quadrants divided by water channels, an image of paradise that the Persian king gave the world. The plan travelled east into India and west into Spain, through every Islamic court and back again, until every walled garden in the world became a reflection of this one.",
                    accent = MythColors.Emerald,
                    stats = listOf(
                        PlaceStat("Tomb height", "11 m"),
                        PlaceStat("Garden quadrants", "4"),
                        PlaceStat("Founder's reign", "29 yrs"),
                        PlaceStat("Stones cut", "3200"),
                        PlaceStat("Aqueducts", "6"),
                        PlaceStat("Steps to tomb", "6"),
                    ),
                    characters = listOf(
                        hc("cassandane", "Cassandane", "Beloved queen", "♡", MythColors.GoldBright, "Mother of kings", 35, 78, 60, 72, 20),
                    ),
                ),
                HistoricPlace(
                    id = "behistun",
                    name = "Behistun",
                    type = PlaceType.Mountain,
                    relPos = Offset(0.30f, 0.20f),
                    era = "521 BC",
                    synopsis = "Cliff of three tongues.",
                    story = "On a sheer rock Darius carved his victory in Old Persian, Elamite, and Babylonian — the Rosetta stone of cuneiform. For two thousand years no one could read it. Rawlinson hung over the cliff with a ladder and a ream of paper, copying every wedge by hand. When the script was cracked, a lost language spoke again. The inscription is a confession and a boast: nine kings in a year Darius defeated, 'by the grace of Ahuramazda'; and the faces of his rebels still lie trampled beneath his boot, carved three hundred feet up the living stone.",
                    accent = MythColors.CyanBright,
                    stats = listOf(
                        PlaceStat("Height", "100 m"),
                        PlaceStat("Languages", "3"),
                        PlaceStat("Carved lines", "1119"),
                        PlaceStat("Figures", "14"),
                        PlaceStat("Rawlinson climbs", "23"),
                        PlaceStat("Wedges copied", "15k"),
                    ),
                    characters = listOf(
                        hc("gaumata", "Gaumata", "False Smerdis", "◈", MythColors.Crimson, "The usurper", 50, 70, 55, 95, 10),
                        hc("rawlinson", "Rawlinson", "Decipherer", "✦", MythColors.CyanBright, "Cliff-climber", 40, 95, 68, 80, 5),
                    ),
                ),
                HistoricPlace(
                    id = "ecbatana",
                    name = "Ecbatana",
                    type = PlaceType.City,
                    relPos = Offset(0.46f, 0.28f),
                    era = "c. 700 BC",
                    synopsis = "Seven-walled summer capital.",
                    story = "Circled by seven concentric walls, each painted a colour of the planets. Here the Medes ruled before Cyrus took it, and here Alexander's general Parmenion hid the treasure of empires. Herodotus called it the summer seat; the snows made it livable while Susa baked. Beneath the modern city of Hamadan lies a mound no archaeologist has been allowed to fully open. What gold still lies in its foundations is anyone's guess — and a jealous one.",
                    accent = MythColors.Azure,
                    stats = listOf(
                        PlaceStat("Walls", "7"),
                        PlaceStat("Elevation", "1900 m"),
                        PlaceStat("Treasure lost", "∞"),
                        PlaceStat("Wall colours", "7"),
                        PlaceStat("Gold vessels", "7k"),
                        PlaceStat("Summer length", "4 mo"),
                    ),
                    characters = listOf(
                        hc("deioces", "Deioces", "First Median king", "♛", MythColors.GoldBright, "Wall-raiser", 75, 82, 72, 86, 15),
                        hc("astyages", "Astyages", "Last of the Medes", "◈", MythColors.Crimson, "Grandfather of Cyrus", 70, 68, 65, 70, 12),
                    ),
                ),
            ),
        ),
        AncientRealm(
            id = "shinar",
            name = "Shinar",
            tagline = "Cradle between the rivers",
            era = "c. 3500 – 539 BC",
            accent = MythColors.Azure,
            mapStyle = MapStyle.Shinar,
            places = listOf(
                HistoricPlace(
                    id = "babylon",
                    name = "Babylon",
                    type = PlaceType.City,
                    relPos = Offset(0.48f, 0.48f),
                    era = "c. 1894 BC",
                    synopsis = "Gate of the gods.",
                    story = "Beneath the Ishtar gate blue with glazed lions, Nebuchadnezzar raised terraced gardens for a homesick queen. Here Hammurabi wrote law onto stone, and here Belshazzar saw the writing on the wall. The Tower of Babel rose in seven stages, a ziggurat to heaven; astronomers on its summit read the sky for centuries and gave the world the hour, the minute, the sexagesimal day. When Cyrus took the city he diverted the Euphrates, waded his armies under the walls by moonlight, and caught the Babylonians mid-feast.",
                    accent = MythColors.Azure,
                    stats = listOf(
                        PlaceStat("Inner walls", "8 km"),
                        PlaceStat("Ishtar gate", "15 m"),
                        PlaceStat("Laws (Hamm.)", "282"),
                        PlaceStat("Glazed lions", "120"),
                        PlaceStat("Ziggurat stages", "7"),
                        PlaceStat("Base number", "60"),
                    ),
                    characters = listOf(
                        hc("hammurabi", "Hammurabi", "Law-giver", "◈", MythColors.Gold, "Sun-king of Babylon", 80, 94, 92, 88, 20),
                        hc("nebuchadnezzar", "Nebuchadnezzar", "Garden king", "♛", MythColors.GoldBright, "Exiler of Jerusalem", 82, 85, 95, 82, 22),
                        hc("ishtar", "Ishtar", "Queen of heavens", "☉", MythColors.Crimson, "Star of Ea", 80, 85, 92, 90, 100),
                    ),
                ),
                HistoricPlace(
                    id = "ur",
                    name = "Ur",
                    type = PlaceType.Temple,
                    relPos = Offset(0.60f, 0.78f),
                    era = "c. 3800 BC",
                    synopsis = "Ziggurat of the moon.",
                    story = "Stepped brick rising to the altar of Nanna, whose silver ship crossed the night sky. From this city Abraham was said to have set out, carrying a new name for God. Leonard Woolley's spade found the royal tombs of Queen Puabi, her attendants and oxen arranged to serve her in the afterlife — a death pageant that shocked a century. The Standard of Ur, a wooden box inlaid with lapis lazuli and shell, showed peace on one side and war on the other, and the beginning of history on both.",
                    accent = MythColors.Sky,
                    stats = listOf(
                        PlaceStat("Ziggurat height", "21 m"),
                        PlaceStat("Royal graves", "17"),
                        PlaceStat("Brick count", "720k"),
                        PlaceStat("Puabi attendants", "74"),
                        PlaceStat("Standard panels", "4"),
                        PlaceStat("Lapis bulls", "3"),
                    ),
                    characters = listOf(
                        hc("urnammu", "Ur-Nammu", "Law-giver", "◉", MythColors.Gold, "Lawgiver of Ur", 72, 90, 80, 80, 15),
                        hc("puabi", "Puabi", "Queen in gold", "♡", MythColors.GoldBright, "Lady in gold", 42, 78, 75, 76, 22),
                        hc("abraham", "Abraham", "Wanderer", "☽", MythColors.CyanBright, "Father of many", 55, 94, 95, 80, 85),
                    ),
                ),
                HistoricPlace(
                    id = "nineveh",
                    name = "Nineveh",
                    type = PlaceType.City,
                    relPos = Offset(0.60f, 0.18f),
                    era = "c. 6000 BC",
                    synopsis = "Lion of Assyria.",
                    story = "Walls so vast three chariots raced abreast upon them, a library of 30 thousand tablets beneath its palaces. Jonah was sent here. A flood of Tigris finally drowned its kings. Ashurbanipal collected every cuneiform tablet his scribes could copy; from that library the Epic of Gilgamesh survived, found in fragments beneath the burned roof of the royal palace. When Medes and Babylonians broke the wall at last, the king set fire to his own palace and threw himself into the flames with his wives.",
                    accent = MythColors.Crimson,
                    stats = listOf(
                        PlaceStat("Wall circ.", "12 km"),
                        PlaceStat("Library tablets", "30k"),
                        PlaceStat("Gates", "15"),
                        PlaceStat("Chariots abreast", "3"),
                        PlaceStat("Wall height", "30 m"),
                        PlaceStat("Destroyed", "612 BC"),
                    ),
                    characters = listOf(
                        hc("sennacherib", "Sennacherib", "Storm-king", "⚔", MythColors.Crimson, "Destroyer of Babylon", 90, 80, 85, 80, 15),
                        hc("ashurbanipal", "Ashurbanipal", "Lion-hunter", "◈", MythColors.GoldBright, "Library-keeper", 88, 92, 88, 82, 20),
                        hc("jonah", "Jonah", "Reluctant prophet", "☽", MythColors.Emerald, "Whale-swallowed", 28, 82, 70, 50, 68),
                    ),
                ),
                HistoricPlace(
                    id = "uruk",
                    name = "Uruk",
                    type = PlaceType.Sanctuary,
                    relPos = Offset(0.38f, 0.70f),
                    era = "c. 4500 BC",
                    synopsis = "Home of Gilgamesh.",
                    story = "First true city in the world. Here writing was born on clay, here kings were kept alive in myth. Gilgamesh walked its walls and sought in the Cedar Forest what no mortal may find. Inanna descended from the heights to the underworld, and her absence left the fields barren until a kid was substituted in her place. The scribes pressed reeds into clay and invented lists — of kings, of fields, of the gods who owned the fields — and from those lists came every ledger and every history the world has written since.",
                    accent = MythColors.Emerald,
                    stats = listOf(
                        PlaceStat("Earliest writing", "3400 BC"),
                        PlaceStat("Population", "40k"),
                        PlaceStat("Epic tablets", "12"),
                        PlaceStat("Wall length", "9 km"),
                        PlaceStat("Temple layers", "18"),
                        PlaceStat("Cylinder seals", "5k"),
                    ),
                    characters = listOf(
                        hc("gilgamesh", "Gilgamesh", "Two-thirds god", "♛", MythColors.Gold, "Sleepless king", 96, 85, 100, 80, 88),
                        hc("enkidu", "Enkidu", "Wild-born friend", "⚔", MythColors.Emerald, "Clay-made equal", 94, 70, 82, 60, 70),
                        hc("inanna", "Inanna", "Queen of heavens", "✦", MythColors.GoldBright, "Lady of the seven gates", 82, 92, 94, 90, 100),
                    ),
                ),
            ),
        ),
        AncientRealm(
            id = "zhongguo",
            name = "Zhongguo",
            tagline = "Kingdom of the central flower",
            era = "c. 2100 BC – 220 AD",
            accent = MythColors.Crimson,
            mapStyle = MapStyle.Zhongguo,
            places = listOf(
                HistoricPlace(
                    id = "taishan",
                    name = "Mount Tai",
                    type = PlaceType.Mountain,
                    relPos = Offset(0.72f, 0.36f),
                    era = "Ages untold",
                    synopsis = "Peak where emperors bowed.",
                    story = "For three thousand years the first peak of China. Seventy-two emperors climbed its 6660 steps to offer Feng and Shan — the rites that bound heaven and earth to their throne. Poets cut their lines into its boulders; the summit holds a forest of stelae, two thousand years of verse stroked onto living rock. At dawn the sea of clouds below turns the mountain into an island of the sky. Confucius, standing at its foot, declared the world small; one step higher and the empire itself looked like a plain.",
                    accent = MythColors.GoldBright,
                    stats = listOf(
                        PlaceStat("Height", "1545 m"),
                        PlaceStat("Stone steps", "6660"),
                        PlaceStat("Imperial rites", "72"),
                        PlaceStat("Summit stelae", "2k"),
                        PlaceStat("Temples", "22"),
                        PlaceStat("Pilgrims / yr", "6 M"),
                    ),
                    characters = listOf(
                        hc("qinshihuang", "Qin Shi Huang", "First emperor", "♛", MythColors.Crimson, "Tiger of Qin", 90, 86, 100, 98, 40),
                        hc("confucius", "Confucius", "Sage of Lu", "◈", MythColors.Gold, "Great sage", 30, 100, 98, 85, 25),
                        hc("huangdi", "Huang Di", "Yellow emperor", "☀", MythColors.GoldBright, "Forefather of Han", 90, 95, 92, 85, 90),
                    ),
                ),
                HistoricPlace(
                    id = "xianyang",
                    name = "Xianyang",
                    type = PlaceType.City,
                    relPos = Offset(0.42f, 0.54f),
                    era = "350 BC",
                    synopsis = "Capital of the first empire.",
                    story = "Qin Shi Huang unified the warring states here and buried with himself an army of 8000 terracotta soldiers in trenches of rammed earth, facing east to guard him for eternity. Each face was sculpted individually; each weapon, a bronze crossbow or halberd, was once chromium-plated against rust. The tomb itself is unopened, sealed beneath a mountain of tamped earth and, if Sima Qian is to be believed, rivers of mercury flowing to model the seas. Soil tests above the mound still read as unusually poisonous.",
                    accent = MythColors.Crimson,
                    stats = listOf(
                        PlaceStat("Terracotta army", "8k"),
                        PlaceStat("Palaces", "270"),
                        PlaceStat("Unification", "221 BC"),
                        PlaceStat("Tomb mound", "76 m"),
                        PlaceStat("Mercury rivers", "100"),
                        PlaceStat("Sealed since", "210 BC"),
                    ),
                    characters = listOf(
                        hc("lisi", "Li Si", "Legalist scribe", "◈", MythColors.Gold, "The chancellor", 35, 96, 75, 98, 8),
                        hc("mengtian", "Meng Tian", "Wall-builder", "⚔", MythColors.GoldBright, "General of the wall", 88, 80, 80, 75, 10),
                    ),
                ),
                HistoricPlace(
                    id = "luoyang",
                    name = "Luoyang",
                    type = PlaceType.City,
                    relPos = Offset(0.54f, 0.42f),
                    era = "c. 1600 BC",
                    synopsis = "Nine dynasties' seat.",
                    story = "On the banks of the Luo, capital to the Shang, the Zhou, the Han, and more. Here silk road caravans ended, and here the first Buddhist temple in China rose among white horses. Thirteen dynasties counted Luoyang as their seat; the longest-inhabited capital in all of Chinese history. Cave temples at Longmen held a hundred thousand carved Buddhas in the cliffs above the river, each face sculpted in devotion over three centuries. The scholars of the Eastern Han invented paper in its workshops — a thin white sheet that put the world into books.",
                    accent = MythColors.Gold,
                    stats = listOf(
                        PlaceStat("Dynasties", "13"),
                        PlaceStat("Silk road end", "East"),
                        PlaceStat("First Buddh. temple", "68 AD"),
                        PlaceStat("Longmen Buddhas", "100k"),
                        PlaceStat("Peak pop.", "500k"),
                        PlaceStat("City walls", "8 km"),
                    ),
                    characters = listOf(
                        hc("wuzhou", "Wu of Zhou", "Founding king", "♛", MythColors.Gold, "Mandate-bearer", 85, 82, 86, 78, 20),
                        hc("empresswu", "Empress Wu", "Sole empress", "☼", MythColors.GoldBright, "Only empress regnant", 70, 90, 92, 98, 30),
                        hc("whitehorse", "White Horse monk", "Sutra bearer", "✦", MythColors.CyanBright, "Carrier of the scrolls", 25, 88, 68, 65, 75),
                    ),
                ),
                HistoricPlace(
                    id = "greatwall",
                    name = "Great Wall",
                    type = PlaceType.Battle,
                    relPos = Offset(0.50f, 0.14f),
                    era = "221 BC",
                    synopsis = "Dragon of stone.",
                    story = "Across the northern steppe a wall was raised against the Xiongnu — earth piled by a million hands, later faced in stone. It was said the bones of the workers were its mortar. Meng Tian drove his conscripts to the horizon; a thousand years later the Ming faced the old wall in brick, battlement by battlement, until the dragon lay more solid than a dream. From space, alas, it is not quite visible. But on a clear morning, from any watchtower, you can see the wall running into the next watchtower and the next, until the earth's curve pulls them under.",
                    accent = MythColors.CyanBright,
                    stats = listOf(
                        PlaceStat("Length", "8850 km"),
                        PlaceStat("Watchtowers", "25k"),
                        PlaceStat("Workers", "1 M"),
                        PlaceStat("Ming brick layers", "900k"),
                        PlaceStat("Beacon signals", "7"),
                        PlaceStat("Highest pass", "1500 m"),
                    ),
                    characters = listOf(
                        hc("mulan", "Mulan", "Warrior-daughter", "◈", MythColors.GoldBright, "Taker of father's sword", 92, 82, 92, 88, 30),
                        hc("xiongnu", "Xiongnu Chanyu", "Steppe lord", "☼", MythColors.Gold, "Horse-lord of the north", 88, 72, 80, 75, 25),
                    ),
                ),
            ),
        ),
        AncientRealm(
            id = "mayab",
            name = "Mayab",
            tagline = "Jungle of feathered kings",
            era = "c. 2000 BC – 900 AD",
            accent = MythColors.Emerald,
            mapStyle = MapStyle.Mayab,
            places = listOf(
                HistoricPlace(
                    id = "tikal",
                    name = "Tikal",
                    type = PlaceType.Temple,
                    relPos = Offset(0.38f, 0.58f),
                    era = "c. 400 BC",
                    synopsis = "City in the canopy.",
                    story = "Pyramids rising above the treetops, painted red against the green. Here the Snake dynasty and the Jaguar dynasty fought a war that echoed for centuries across Petén. Jasaw Chan K'awiil I captured the Calakmul lord and founded a golden age; his tomb, buried in Temple I, held jade, obsidian, and a single sting-ray spine for the ritual blood-letting that was the bread of kings. When drought broke the kingdom, the court left one morning and the forest took it back in a hundred summers.",
                    accent = MythColors.Emerald,
                    stats = listOf(
                        PlaceStat("Pyramids", "6"),
                        PlaceStat("Tallest", "64 m"),
                        PlaceStat("Peak pop.", "90k"),
                        PlaceStat("Stelae", "200+"),
                        PlaceStat("Dynasty span", "800 yrs"),
                        PlaceStat("Jade (tomb)", "180 pcs"),
                    ),
                    characters = listOf(
                        hc("yaxehb", "Yax Ehb' Xook", "Founder", "♛", MythColors.Gold, "Firstborn of Tikal", 75, 82, 80, 75, 25),
                        hc("jasaw", "Jasaw Chan", "Snake-crusher", "⚔", MythColors.Emerald, "Sun-bearer", 90, 84, 90, 82, 35),
                        hc("ixtekab", "Ix Te' K'ab", "Warrior queen", "✦", MythColors.GoldBright, "Tree-hand lady", 82, 80, 80, 82, 30),
                    ),
                ),
                HistoricPlace(
                    id = "chichen",
                    name = "Chichén Itzá",
                    type = PlaceType.Sanctuary,
                    relPos = Offset(0.62f, 0.28f),
                    era = "c. 600 AD",
                    synopsis = "Serpent on the steps.",
                    story = "At equinox the sun throws a descending serpent down the pyramid of Kukulkan. A sacred cenote devoured offerings of jade and maidens, keeping the rain-lord Chaac fed. The ball court was the largest in Mesoamerica — its captains played a game whose losers gave up their heads. Sound claps echoing between the walls still answer a visitor's call seven times before falling silent. The builders aligned the whole complex so that at specific dates a shadow would move just so; the stone clockwork was their priest-king's calendar, and his right to rule.",
                    accent = MythColors.CyanBright,
                    stats = listOf(
                        PlaceStat("Pyramid steps", "365"),
                        PlaceStat("Cenote depth", "27 m"),
                        PlaceStat("Ball courts", "13"),
                        PlaceStat("Chaac masks", "260"),
                        PlaceStat("Clap echoes", "7"),
                        PlaceStat("Skulls (tzomp.)", "532"),
                    ),
                    characters = listOf(
                        hc("kukulkan", "Kukulkan", "Feathered serpent", "☼", MythColors.Gold, "Plumed one", 92, 95, 98, 90, 100),
                        hc("chaac", "Chaac", "Rain lord", "☁", MythColors.CyanBright, "Lord of the axe-storm", 88, 75, 85, 70, 98),
                        hc("hunahpu", "Hunahpu", "Hero-twin", "⚔", MythColors.Emerald, "Ball-player twin", 94, 82, 88, 90, 82),
                    ),
                ),
                HistoricPlace(
                    id = "palenque",
                    name = "Palenque",
                    type = PlaceType.City,
                    relPos = Offset(0.24f, 0.42f),
                    era = "c. 226 BC",
                    synopsis = "Tomb of Pakal the Great.",
                    story = "Below the Temple of Inscriptions, a stone sarcophagus carved with the king descending into the maw of the underworld. For 68 years Pakal ruled, and his lid was read as a starship by those who dreamed. His tomb was the first undisturbed royal burial found in Mesoamerica; the jade mosaic on his face looked out again upon a sky he had not seen in thirteen hundred years. The inscriptions named him 'He of the Five Platforms' and 'Lord of Twenty Captives'; his son carved stone portraits of his father that still look back at the forest with a king's steady patience.",
                    accent = MythColors.Sky,
                    stats = listOf(
                        PlaceStat("Pakal reign", "68 yrs"),
                        PlaceStat("Temple height", "27 m"),
                        PlaceStat("Glyph panels", "617"),
                        PlaceStat("Jade tesserae", "340"),
                        PlaceStat("Tomb depth", "25 m"),
                        PlaceStat("Undisturbed", "1300 yrs"),
                    ),
                    characters = listOf(
                        hc("pakal", "Pakal", "Shield of the sun", "♛", MythColors.GoldBright, "The Great Sun-Shield", 72, 90, 98, 85, 55),
                        hc("tzakbu", "Tz'akbu Ajaw", "Red queen", "♡", MythColors.Crimson, "Lady of cinnabar", 55, 85, 75, 82, 30),
                        hc("kanbahlam", "Kan Bahlam", "Snake-jaguar", "⚔", MythColors.Emerald, "Serpent-paw", 85, 85, 82, 82, 35),
                    ),
                ),
                HistoricPlace(
                    id = "copan",
                    name = "Copán",
                    type = PlaceType.Temple,
                    relPos = Offset(0.52f, 0.78f),
                    era = "c. 100 AD",
                    synopsis = "Athens of the Maya.",
                    story = "A stairway carved with 2200 glyphs tells the city's dynasty. Here '18 Rabbit' was captured and beheaded by a rival king, and the court's sculptors raised portrait stelae as tall as trees. The Hieroglyphic Stairway is the longest Maya text ever carved; when it collapsed the blocks tumbled out of sequence, and scholars have been re-ordering the sentences since. The sculptors of Copán were its pride — their portraits were round and hooded with feathers, the faces finer than anywhere else in the Maya world.",
                    accent = MythColors.GoldBright,
                    stats = listOf(
                        PlaceStat("Glyph steps", "2200"),
                        PlaceStat("Stelae", "38"),
                        PlaceStat("Dynasty years", "400"),
                        PlaceStat("Kings", "16"),
                        PlaceStat("Altar Q figures", "16"),
                        PlaceStat("Ball courts", "1"),
                    ),
                    characters = listOf(
                        hc("yaxkuk", "Yax K'uk' Mo'", "Founder-lord", "◉", MythColors.Gold, "First macaw-sun", 80, 80, 78, 75, 25),
                        hc("rabbit18", "18 Rabbit", "Patron of arts", "✦", MythColors.Emerald, "Sculptor-king", 70, 90, 85, 72, 22),
                        hc("smokeshell", "Smoke Shell", "Final scribe", "◈", MythColors.Crimson, "Keeper of glyphs", 40, 90, 55, 78, 10),
                    ),
                ),
            ),
        ),
        AncientRealm(
            id = "latium",
            name = "Latium",
            tagline = "The wolf's seven hills",
            era = "c. 753 BC – 476 AD",
            accent = MythColors.Gold,
            mapStyle = MapStyle.Latium,
            places = listOf(
                HistoricPlace(
                    id = "rome",
                    name = "Roma",
                    type = PlaceType.City,
                    relPos = Offset(0.38f, 0.30f),
                    era = "753 BC",
                    synopsis = "Eternal city on seven hills.",
                    story = "Romulus drew a furrow on the Palatine, killed his brother for crossing it, and the world's longest story began. Forum, Colosseum, Pantheon — stones that ruled half a planet. The aqueducts brought rivers down from the Sabine hills; the Cloaca Maxima took them away; in between, citizens bathed in marble and plotted the fate of provinces. At its peak one in every five humans lived under Roman law. The city fell, rose, fell again, and yet its streets are still walked upon; its name still honoured; its tongue — Latin — still speaks through every law court in Europe.",
                    accent = MythColors.Gold,
                    stats = listOf(
                        PlaceStat("Seven hills", "7"),
                        PlaceStat("Peak pop.", "1 M"),
                        PlaceStat("Emperors", "141"),
                        PlaceStat("Aqueducts", "11"),
                        PlaceStat("Roads", "400k km"),
                        PlaceStat("Provinces", "46"),
                    ),
                    characters = listOf(
                        hc("romulus", "Romulus", "Founder-twin", "⚔", MythColors.Crimson, "Wolf-suckled", 90, 70, 98, 82, 65),
                        hc("caesar", "Caesar", "Ides-felled", "◈", MythColors.Gold, "Dictator perpetuo", 95, 95, 100, 98, 30),
                        hc("augustus", "Augustus", "First citizen", "♛", MythColors.GoldBright, "Princeps", 75, 96, 100, 100, 45),
                    ),
                ),
                HistoricPlace(
                    id = "pompeii",
                    name = "Pompeii",
                    type = PlaceType.Battle,
                    relPos = Offset(0.58f, 0.66f),
                    era = "79 AD",
                    synopsis = "Frozen under ash.",
                    story = "On the 24th of August Vesuvius turned daylight to night and buried a city alive. The frescoes, loaves of bread, and the casts of sleepers remained for seventeen centuries under the grey. Graffiti on the walls still joke and insult; a child's wooden cradle still rocked. When Fiorelli poured plaster into the voids where the dead had decayed, their last postures came back into the world — a merchant clutching his purse, a family curled around a dog, a pregnant woman still trying to breathe through the ashfall. It is the most detailed day in the entire Roman world.",
                    accent = MythColors.Crimson,
                    stats = listOf(
                        PlaceStat("Ash depth", "6 m"),
                        PlaceStat("Frozen pop.", "2k"),
                        PlaceStat("Plaster casts", "100+"),
                        PlaceStat("Wall inscriptions", "11k"),
                        PlaceStat("Frescoes intact", "80%"),
                        PlaceStat("Years sealed", "1700"),
                    ),
                    characters = listOf(
                        hc("plinyelder", "Pliny Elder", "Naturalist", "✦", MythColors.Gold, "Died at the shore", 30, 96, 82, 78, 5),
                        hc("rectina", "Rectina", "Rescued lady", "♡", MythColors.GoldBright, "Lady of the bay", 25, 70, 30, 65, 5),
                        hc("juliafelix", "Julia Felix", "Villa-keeper", "◈", MythColors.Emerald, "Leasor of pleasures", 35, 75, 50, 70, 4),
                    ),
                ),
                HistoricPlace(
                    id = "ostia",
                    name = "Ostia",
                    type = PlaceType.City,
                    relPos = Offset(0.30f, 0.46f),
                    era = "c. 620 BC",
                    synopsis = "Port of the empire.",
                    story = "At the mouth of the Tiber, grain from Egypt and oil from Hispania fed a million Romans. Amphorae beyond counting, warehouses a half-mile long, sailors from every shore of the middle sea. The Piazzale delle Corporazioni held 61 mosaic shopfronts — ship agents advertising their home ports in black-and-white stones that still show a dolphin, a corn measure, a lighthouse. When the Tiber silted up, the port moved inland; the city above, abandoned, preserved its apartment blocks and temples in a completeness that Rome itself cannot match.",
                    accent = MythColors.Sky,
                    stats = listOf(
                        PlaceStat("Warehouse area", "60k m²"),
                        PlaceStat("Grain / yr", "400k t"),
                        PlaceStat("Guilds", "57"),
                        PlaceStat("Amphorae found", "25 M"),
                        PlaceStat("Mosaic shops", "61"),
                        PlaceStat("City span", "3 km"),
                    ),
                    characters = listOf(
                        hc("ancus", "Ancus Marcius", "Fourth king", "♛", MythColors.Gold, "Salt-road builder", 78, 80, 75, 75, 20),
                        hc("trajan", "Trajan", "Port-builder", "◈", MythColors.GoldBright, "Optimus princeps", 92, 90, 95, 90, 25),
                        hc("hilarinus", "Hilarinus", "Amphora-master", "⚔", MythColors.Crimson, "Master of the amphorae", 50, 72, 30, 65, 3),
                    ),
                ),
                HistoricPlace(
                    id = "cumae",
                    name = "Cumae",
                    type = PlaceType.Sanctuary,
                    relPos = Offset(0.52f, 0.78f),
                    era = "c. 750 BC",
                    synopsis = "Cave of the Sibyl.",
                    story = "In a rock-hewn gallery the Cumaean Sibyl sang the fate of Rome on leaves the wind scattered. Aeneas descended from here to the underworld, and the books she sold to Tarquin counselled the Republic for five hundred years. When three of the nine books were burnt the price went up; Tarquin paid in full for the remaining three. The Temple of Jupiter kept them in vaults until fire took them in 83 BC. Roman generals at crossroads of the state — plague, famine, foreign war — would bring their senatorial question to the books, and the book would answer in hexameter.",
                    accent = MythColors.Emerald,
                    stats = listOf(
                        PlaceStat("Gallery length", "131 m"),
                        PlaceStat("Sibylline books", "9"),
                        PlaceStat("Oracle span", "500 yrs"),
                        PlaceStat("Gallery age", "2.5 k yrs"),
                        PlaceStat("Books burnt", "6"),
                        PlaceStat("Vault fires", "2"),
                    ),
                    characters = listOf(
                        hc("sibyl", "Cumaean Sibyl", "Leaf-writer", "☽", MythColors.Emerald, "Voice of the leaves", 30, 97, 88, 78, 82),
                        hc("aeneas", "Aeneas", "Trojan wanderer", "⚔", MythColors.Gold, "Father of Rome", 90, 82, 95, 80, 70),
                        hc("tarquin", "Tarquin", "Book-buyer king", "◈", MythColors.Crimson, "The proud", 68, 72, 68, 82, 12),
                    ),
                ),
            ),
        ),
    )

    val allCharacters: List<HistoricCharacter> by lazy {
        realms.flatMap { it.places }.flatMap { it.characters }.distinctBy { it.id }.sortedBy { it.name }
    }

    fun findRealmOf(charId: String): AncientRealm? =
        realms.firstOrNull { it.places.any { p -> p.characters.any { c -> c.id == charId } } }
}
